// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package encode.array.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The NewlineDelimitedExtensibleEnumArrayProperty model.
 */
@Immutable
public final class NewlineDelimitedExtensibleEnumArrayProperty
    implements JsonSerializable<NewlineDelimitedExtensibleEnumArrayProperty> {
    /*
     * The value property.
     */
    @Generated
    private final List<ColorsExtensibleEnum> value;

    /**
     * Creates an instance of NewlineDelimitedExtensibleEnumArrayProperty class.
     * 
     * @param value the value value to set.
     */
    @Generated
    public NewlineDelimitedExtensibleEnumArrayProperty(List<ColorsExtensibleEnum> value) {
        this.value = value;
    }

    /**
     * Get the value property: The value property.
     * 
     * @return the value value.
     */
    @Generated
    public List<ColorsExtensibleEnum> getValue() {
        return this.value;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        if (this.value != null) {
            jsonWriter.writeStringField("value",
                this.value.stream()
                    .map(element -> element == null ? null : element.toString())
                    .collect(Collectors.joining("\n")));
        }
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of NewlineDelimitedExtensibleEnumArrayProperty from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of NewlineDelimitedExtensibleEnumArrayProperty if the JsonReader was pointing to an instance
     * of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the NewlineDelimitedExtensibleEnumArrayProperty.
     */
    @Generated
    public static NewlineDelimitedExtensibleEnumArrayProperty fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            List<ColorsExtensibleEnum> value = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    value = reader.getNullable(nonNullReader -> {
                        String valueEncodedAsString = nonNullReader.getString();
                        return valueEncodedAsString.isEmpty()
                            ? new LinkedList<>()
                            : new LinkedList<>(Arrays.stream(valueEncodedAsString.split("\n", -1))
                                .map(valueAsString -> valueAsString == null
                                    ? null
                                    : ColorsExtensibleEnum.fromString(valueAsString))
                                .collect(Collectors.toList()));
                    });
                } else {
                    reader.skipChildren();
                }
            }
            return new NewlineDelimitedExtensibleEnumArrayProperty(value);
        });
    }
}
