// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the data models for Array.
 * Test for encode decorator on array.
 * <!-- end generated doc -->
 */
package encode.array.models;
