trigger:
  branches:
    include:
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - main
      - release/*

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    BinSkimSettings:
      analyzeTargetGlob: +:file|**/*.dll;+:file|**/*.exe;-:f|**/tsp.exe # Flag issue with node binary which we can't fix https://github.com/nodejs/node/issues/42100
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - task: NodeTool@0
                displayName: Install Node.js
                inputs:
                  versionSpec: 22.x
              - script: npm install -g pnpm # Pnpm manage-package-manager-versions will respect packageManager field
                displayName: Install pnpm

              - script: pnpm install
                displayName: Install JavaScript Dependencies

              - script: node $(Build.SourcesDirectory)/eng/common/scripts/resolve-target-branch.js
                displayName: Resolve target branch

              - script: pnpm tsx ./eng/common/scripts/dispatch-area-triggers.ts --target-branch $(TARGET_BRANCH)
                displayName: "Analyze PR changes"
                name: InitStep

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run java stages if RunJava == true
      - template: /packages/http-client-java/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunJava'])

      # Run python stages if RunPython == true
      - template: /packages/http-client-python/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunPython'])

      # Run core stages if RunCore == true
      - template: /eng/tsp-core/pipelines/stages/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])
