trigger:
  branches:
    include:
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - main
      - release/*

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - script: npm install -g pnpm # Pnpm manage-package-manager-versions will respect packageManager field
                displayName: Install pnpm

              - script: pnpm install
                displayName: Install JavaScript Dependencies

              - script: node $(Build.SourcesDirectory)/eng/common/scripts/resolve-target-branch.js
                displayName: Resolve target branch

              - script: pnpm tsx ./eng/common/scripts/dispatch-area-triggers.ts --target-branch $(TARGET_BRANCH)
                displayName: "Analyze PR changes"
                name: InitStep
              - script: |
                  if git diff --name-only $(Build.SourceVersion) $(Build.SourceBranch) | grep -qv 'website/src/content/docs/docs/release-notes/'; then
                    echo "##vso[task.setvariable variable=only_release_notes_changes]false"
                  else
                    echo "##vso[task.setvariable variable=only_release_notes_changes]true"
                  fi
                displayName: Check if only release notes changed

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run java stages if RunJava == true
      - template: /packages/http-client-java/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunJava'])

      # Run python stages if RunPython == true
      - template: /packages/http-client-python/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunPython'])

      # Run core stages if RunCore == true
      - template: /eng/tsp-core/pipelines/stages/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: and(eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore']), eq(variables['only_release_notes_changes'], 'false'))
