trigger:
  branches:
    include:
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - main

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - script: |
                  corepack enable
                  corepack prepare pnpm --activate
                displayName: Install pnpm

              - script: pnpm install
                displayName: Install JavaScript Dependencies

              - script: node $(Build.SourcesDirectory)/eng/common/scripts/resolve-target-branch.js
                displayName: Resolve target branch

              - script: pnpm tsx ./eng/common/scripts/dispatch-area-triggers.ts --target-branch $(TARGET_BRANCH)
                displayName: "Analyze PR changes"
                name: InitStep

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run core stages if RunCore == true
      - template: /eng/tsp-core/pipelines/stages/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])
