trigger:
  branches:
    include:
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - main

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    stages:
      - stage: InitStage
        displayName: Initialize
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: InitJob
            displayName: Initialize
            steps:
              - script: node $(Build.SourcesDirectory)/eng/common/scripts/resolve-target-branch.js
                displayName: Resolve target branch

              - task: PowerShell@2
                displayName: "Analyze PR changes"
                name: InitStep
                inputs:
                  pwsh: true
                  filePath: $(Build.SourcesDirectory)/eng/common/scripts/Analyze-Changes.ps1
                  arguments: >
                    -TargetBranch $(TARGET_BRANCH)
                  workingDirectory: $(Build.SourcesDirectory)

      # Run csharp stages if RunCSharp == true
      - template: /packages/http-client-csharp/eng/pipeline/templates/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCSharp'])

      # Run core stages if RunCore == true
      - template: /eng/tsp-core/pipelines/stages/ci-stages.yml
        parameters:
          DependsOn: InitStage
          Condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])

      # Run eng test stage if RunEng == true
      - stage: EngTest
        displayName: Eng - Test
        dependsOn: InitStage
        condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunEng'])
        jobs:
          - job: EngTest
            displayName: Eng - Test
            pool:
              name: $(LINUXPOOL)
              image: $(LINUXVMIMAGE)
              os: linux
            steps:
              - pwsh: |
                  Write-Host "Installing Pester"
                  Install-Module -Name Pester -RequiredVersion '5.5.0' -Force -SkipPublisherCheck
                  Import-Module Pester

                  Write-Host "Running pester tests"
                  Invoke-Pester
                displayName: "Run pester tests"
                workingDirectory: $(Build.SourcesDirectory)/eng
