id: pr.inactivity
name: GitOps.PullRequestIssueManagement
description: Manage Stale pull requests
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: Ping user when the PR hasn't
        frequencies:
          - daily:
              time: 13:0
        filters:
          - isPullRequest
          - isOpen
          - noActivitySince:
              days: 30
        actions:
          - addLabel:
            label: stale
          - addReply:
              reply: >-
                Hi @${issueAuthor}.
                Your PR has no update for 30 days and it is marked as stale PR. If no further update for over 30 days, the bot will close the PR.  If you want to refresh the PR, please remove `stale` label.

      - description: Close prs that have not been updated in 60 days
        frequencies:
          - daily:
              time: 13:0
        filters:
          - isPullRequest
          - isOpen
          - hasLabel:
              label: no-recent-activity
          - noActivitySince:
              days: 30
        actions:
          - closeIssue
          - addReply:
              reply: >-
                Hi @${issueAuthor}.
                The PR will be closed since the PR has no update for 60 days. If this is still relevant please reopen.

onFailure:
onSuccess:
