id: pr.inactivity
name: GitOps.PullRequestIssueManagement
description: Manage Stale pull requests
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: Ping user when the PR has not been updated in 14 days
        frequencies:
          - daily:
              time: 13:0
        filters:
          - isPullRequest
          - isOpen
          - isNotLabeledWith:
              label: stale
          - noActivitySince:
              days: 14
        actions:
          - addLabel:
              label: stale
          - addReply:
              reply: >-
                Hi @${issueAuthor}.
                Your PR has had no update for 14 days and it is marked as a stale PR. If it is not updated within 14 additional days, the PR will automatically be closed.  If you want to refresh the PR, please remove the `stale` label.

      - description: Close prs that have not been updated in 28 days
        frequencies:
          - daily:
              time: 13:0
        filters:
          - isPullRequest
          - isOpen
          - hasLabel:
              label: stale
          - noActivitySince:
              days: 14
        actions:
          - closeIssue
          - addReply:
              reply: >-
                Hi @${issueAuthor}.
                The PR will be closed since the PR has no update for 28 days. If this is still relevant please reopen.

onFailure:
onSuccess:
