// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.serviceclientnameconflict;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import tsptest.serviceclientnameconflict.implementation.ServiceClientNameConflictClientImpl;

/**
 * Initializes a new instance of the synchronous ServiceClientNameConflictClient type.
 */
@ServiceClient(builder = ServiceClientNameConflictClientBuilder.class)
public final class ServiceClientNameConflictClient {
    @Generated
    private final ServiceClientNameConflictClientImpl serviceClient;

    /**
     * Initializes an instance of ServiceClientNameConflictClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    ServiceClientNameConflictClient(ServiceClientNameConflictClientImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The ping operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * String
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a sequence of textual characters along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> pingWithResponse(RequestOptions requestOptions) {
        return this.serviceClient.pingWithResponse(requestOptions);
    }

    /**
     * The ping operation.
     * 
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a sequence of textual characters.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public String ping() {
        // Generated convenience method for pingWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return pingWithResponse(requestOptions).getValue().toString();
    }
}
