name: PR Tools
trigger: none
pr:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - packages/http-client-csharp
      - cspell.yaml
      - eng/emitters

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
    stages:
      - stage: pr_tools
        displayName: PR Tools
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: tryit
            displayName: Setup Try It
            variables:
              SWA_ENV: "pr$(System.PullRequest.PullRequestNumber)"
            steps:
              - checkout: self
                persistCredentials: true

              - template: /eng/tsp-core/pipelines/templates/install.yml
              - template: /eng/tsp-core/pipelines/templates/install-browsers.yml

              - template: /eng/tsp-core/pipelines/templates/build.yml

              - script: npm install -g @azure/static-web-apps-cli
                displayName: Install SWA CLI

              - task: AzureCLI@1
                displayName: "Publish playground to PR endpoint"
                name: setPlaygroundHostname
                inputs:
                  azureSubscription: "Azure SDK Engineering System"
                  scriptLocation: inlineScript
                  workingDirectory: ./packages/playground-website
                  inlineScript: |
                    swa deploy --env $(SWA_ENV) --verbose=silly

                    hostname=$(az staticwebapp environment show \
                      -n typespec-playground \
                      --environment-name $(SWA_ENV) \
                      --query hostname -o tsv)
                    echo "SWA hostname: $hostname"
                    echo "##vso[task.setvariable variable=PLAYGROUND_HOSTNAME;isOutput=true]$hostname"

              - task: AzureCLI@1
                displayName: "Publish website to PR endpoint"
                name: setWebsiteHostname
                inputs:
                  azureSubscription: "Azure SDK Engineering System"
                  scriptLocation: inlineScript
                  workingDirectory: ./website
                  inlineScript: |
                    swa deploy --env $(SWA_ENV) --verbose=silly

                    hostname=$(az staticwebapp environment show \
                      -n typespec-website \
                      --environment-name $(SWA_ENV) \
                      --query hostname -o tsv)
                    echo "SWA hostname: $hostname"
                    echo "##vso[task.setvariable variable=WEBSITE_HOSTNAME;isOutput=true]$hostname"

              - task: CopyFiles@2
                displayName: "Copy VSCode extension .vsix to artifact directory"
                inputs:
                  SourceFolder: "$(Build.SourcesDirectory)/packages/typespec-vscode"
                  Contents: "*.vsix"
                  TargetFolder: "$(Build.ArtifactStagingDirectory)/vscode-extension"
            templateContext:
              outputs:
                - output: pipelineArtifact
                  path: $(Build.ArtifactStagingDirectory)/vscode-extension
                  artifact: vscode-extension
                  displayName: Copy VSCode extension .vsix to artifact directory
          - job: tryit_comment
            displayName: Create TryIt comment
            dependsOn: tryit
            variables:
              PLAYGROUND_HOSTNAME: $[ dependencies.tryit.outputs['setPlaygroundHostname.PLAYGROUND_HOSTNAME'] ]
              WEBSITE_HOSTNAME: $[ dependencies.tryit.outputs['setWebsiteHostname.WEBSITE_HOSTNAME'] ]
            steps:
              - pwsh: |
                  $curlCommand = 'curl -s -u :$(System.AccessToken) "$(System.TeamFoundationCollectionUri)/$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=vscode-extension"'
                  $response = Invoke-Expression $curlCommand
                  $responseObject = $response | ConvertFrom-Json
                  Write-Host "response: $response"
                  $downloadUrl = $responseObject.resource.downloadUrl
                  Write-Output "Artifact URL: $downloadUrl"
                  Write-Host "##vso[task.setvariable variable=vscodeUrl]$downloadUrl"
                displayName: Get vscode artifact URL

              - script: npx tsx eng/tsp-core/scripts/create-tryit-comment.ts
                displayName: Check already commented
                env:
                  GH_TOKEN: $(azuresdk-github-pat)
                  VSCODE_DOWNLOAD_URL: $(vscodeUrl)
                  WEBSITE_HOSTNAME: $(WEBSITE_HOSTNAME)
                  PLAYGROUND_HOSTNAME: $(PLAYGROUND_HOSTNAME)
