name: PR Tools
trigger: none
pr:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - packages/http-client-csharp
      - cspell.yaml
      - eng/emitters

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
    stages:
      - stage: pr_tools
        displayName: PR Tools
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: tryit
            displayName: Setup Try It
            variables:
              TYPESPEC_WEBSITE_BASE_PATH: "/prs/$(System.PullRequest.PullRequestNumber)/"
            steps:
              - checkout: self
                persistCredentials: true

              - template: /eng/tsp-core/pipelines/templates/install.yml
              - template: /eng/tsp-core/pipelines/templates/install-browsers.yml

              - template: /eng/tsp-core/pipelines/templates/build.yml

              - task: AzureCLI@1
                displayName: "Publish playground to PR endpoint"
                inputs:
                  azureSubscription: "Azure SDK Engineering System"
                  scriptLocation: inlineScript
                  inlineScript: |
                    az storage blob upload-batch \
                      --auth-mode login \
                      --destination \$web \
                      --account-name "cadlplayground" \
                      --destination-path $(TYPESPEC_WEBSITE_BASE_PATH) \
                      --source "./packages/playground-website/dist/web/" \
                      --overwrite

              - task: AzureCLI@1
                displayName: "Publish website to PR endpoint"
                inputs:
                  azureSubscription: "Azure SDK Engineering System"
                  scriptLocation: inlineScript
                  inlineScript: |
                    az storage blob upload-batch \
                      --auth-mode login \
                      --destination \$web \
                      --account-name "tspwebsitepr" \
                      --destination-path $(TYPESPEC_WEBSITE_BASE_PATH) \
                      --source "./website/dist/" \
                      --overwrite

              - task: CopyFiles@2
                displayName: "Copy VSCode extension .vsix to artifact directory"
                inputs:
                  SourceFolder: "$(Build.SourcesDirectory)/packages/typespec-vscode"
                  Contents: "*.vsix"
                  TargetFolder: "$(Build.ArtifactStagingDirectory)/vscode-extension"
              - script: |
                  echo "##[section]Retrieving artifact URL..."
                  artifactUrl=$(curl -s -u :$(System.AccessToken) "$(System.TeamFoundationCollectionUri)/$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactsName=vscode-extension-unsigned&api-version=7.1-preview.5" | jq -r '.value.resource.downloadUrl')
                  echo "##vso[task.setvariable variable=vscodeUrl]$artifactUrl"
                displayName: Get vscode artifact URL

              - script: npx tsx eng/tsp-core/scripts/create-tryit-comment.ts
                displayName: Check already commented
                env:
                  GH_TOKEN: $(azuresdk-github-pat)
                  VSCODE_DOWNLOAD_URL: $(vscodeUrl)

            templateContext:
              outputs:
                - output: pipelineArtifact
                  path: $(Build.ArtifactStagingDirectory)/vscode-extension
                  artifact: vscode-extension-unsigned
                  displayName: Publish VSCode extension(.vsix) as pipeline artifacts

          - job: change_comment
            displayName: Describe changes on PR
            condition: and(succeeded(), eq(startsWith(variables['System.PullRequest.SourceBranch'], 'publish/'), false))
            steps:
              - checkout: self

              - script: npx -p @chronus/github-pr-commenter@0.5.0 chronus-github-pr-commenter
                displayName: Make comment about changes
                env:
                  GITHUB_TOKEN: $(azuresdk-github-pat)
