# Continuous Integration

trigger:
  branches:
    include:
      - main
      - test/vscode-e2e-repro
      # For patch releases
      - release/*
  paths:
    exclude:
      - packages/http-client-csharp
      - packages/http-client-java
      - packages/http-client-python

pr: none

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml
  parameters:
    BinSkimSettings:
      analyzeTargetGlob: +:file|*.exe;-:f|**/tsp.exe # Flag issue with node binary which we can't fix https://github.com/nodejs/node/issues/42100
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self

    stages:
      - stage: build
        dependsOn: []
        displayName: Build

        pool:
          name: $(WINDOWSPOOL)
          image: $(WINDOWSVMIMAGE)
          os: windows

        jobs:
          - template: /eng/tsp-core/pipelines/jobs/build-for-publish.yml@self
          - template: /eng/tsp-core/pipelines/jobs/cli/build-tsp-cli-all.yml@self
          - template: /eng/tsp-core/pipelines/jobs/e2e.yml@self
            parameters:
              azLogin: true

      - stage: publish_npm
        displayName: Publish Npm Packages
        dependsOn: build
        condition: or(eq('true', dependencies.build.outputs['build.pack_npm_packages_stable.PUBLISH_PKG_ANY']), eq('true', dependencies.build.outputs['build.pack_npm_packages_next.PUBLISH_PKG_ANY']))

        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux

        # jobs:
        #   - template: /eng/tsp-core/pipelines/jobs/publish-npm.yml
        #     parameters:
        #       artifactName: npm-packages-stable
        #       tag: latest
        #       condition: eq('true', stageDependencies.build.build.outputs['pack_npm_packages_stable.PUBLISH_PKG_ANY'])

        #   - template: /eng/tsp-core/pipelines/jobs/publish-npm.yml
        #     parameters:
        #       dependsOn: publish_npm_latest
        #       artifactName: npm-packages-next
        #       tag: next
        #       condition: eq('true', stageDependencies.build.build.outputs['pack_npm_packages_next.PUBLISH_PKG_ANY'])

        #   - template: /eng/tsp-core/pipelines/jobs/create-github-release.yml
        #     parameters:
        #       dependsOn: publish_npm_latest
        #       artifactName: npm-packages-stable

      - stage: publish_vscode
        displayName: Publish VSCode extension
        dependsOn: build
        jobs:
          - template: /eng/tsp-core/pipelines/jobs/publish-vscode.yml

      - stage: publish_vs
        displayName: Publish VS extension
        dependsOn: build
        jobs:
          - template: /eng/tsp-core/pipelines/jobs/publish-vs.yml

      - template: /eng/tsp-core/pipelines/stages/sign-publish-tsp-cli.yml@self

      - stage: docker
        displayName: Docker
        dependsOn: []
        jobs:
          - job: docker
            displayName: Build and publish
            variables:
              imageName: "azsdkengsys.azurecr.io/typespec"
            pool:
              name: $(LINUXPOOL)
              image: $(LINUXVMIMAGE)
              os: linux
            steps:
              - task: Docker@1
                displayName: login
                inputs:
                  azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
                  azureContainerRegistry: azsdkengsys.azurecr.io
                  command: login

              - script: |
                  docker build -f ./docker/Dockerfile \
                    -t $(imageName):latest \
                    .
                displayName: "Build"
              - script: docker push $(imageName) --all-tags
                displayName: "Push"
