// <auto-generated/>

#nullable disable

using System.ClientModel.Primitives;
using Sample.Models;

namespace Sample
{
#pragma warning disable CS0618 // global::Sample.Models.CustomizedObsoleteModel is obsolete and may be removed in future versions.
    [global::System.ClientModel.Primitives.ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.CustomizedObsoleteModel))]
#pragma warning restore CS0618 // global::Sample.Models.CustomizedObsoleteModel is obsolete and may be removed in future versions.
    [global::System.ClientModel.Primitives.ModelReaderWriterBuildableAttribute(typeof(global::Sample.Models.RegularModel))]
    public partial class SampleContext : global::System.ClientModel.Primitives.ModelReaderWriterContext
    {
    }
}
