// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for Documentation.
 * Illustrates documentation generation and formatting features.
 * <!-- end generated doc -->
 */
package documentation;
