// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package payload.xml.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.xml.XmlReader;
import com.azure.xml.XmlSerializable;
import com.azure.xml.XmlToken;
import com.azure.xml.XmlWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * §4.3 — Contains a wrapped array of models with a custom wrapper name.
 */
@Immutable
public final class ModelWithRenamedWrappedModelArray implements XmlSerializable<ModelWithRenamedWrappedModelArray> {
    /*
     * The AllItems property.
     */
    @Generated
    private final List<SimpleModel> items;

    /**
     * Creates an instance of ModelWithRenamedWrappedModelArray class.
     * 
     * @param items the items value to set.
     */
    @Generated
    public ModelWithRenamedWrappedModelArray(List<SimpleModel> items) {
        this.items = items;
    }

    /**
     * Get the items property: The AllItems property.
     * 
     * @return the items value.
     */
    @Generated
    public List<SimpleModel> getItems() {
        if (this.items == null) {
            return Collections.emptyList();
        }
        return this.items;
    }

    @Generated
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Generated
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty()
            ? "ModelWithRenamedWrappedModelArray"
            : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        if (this.items != null) {
            xmlWriter.writeStartElement("AllItems");
            for (SimpleModel element : this.items) {
                xmlWriter.writeXml(element, "SimpleModel");
            }
            xmlWriter.writeEndElement();
        }
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of ModelWithRenamedWrappedModelArray from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of ModelWithRenamedWrappedModelArray if the XmlReader was pointing to an instance of it, or
     * null if it was pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ModelWithRenamedWrappedModelArray.
     */
    @Generated
    public static ModelWithRenamedWrappedModelArray fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of ModelWithRenamedWrappedModelArray from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of ModelWithRenamedWrappedModelArray if the XmlReader was pointing to an instance of it, or
     * null if it was pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ModelWithRenamedWrappedModelArray.
     */
    @Generated
    public static ModelWithRenamedWrappedModelArray fromXml(XmlReader xmlReader, String rootElementName)
        throws XMLStreamException {
        String finalRootElementName = rootElementName == null || rootElementName.isEmpty()
            ? "ModelWithRenamedWrappedModelArray"
            : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            List<SimpleModel> items = null;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("AllItems".equals(elementName.getLocalPart())) {
                    while (reader.nextElement() != XmlToken.END_ELEMENT) {
                        elementName = reader.getElementName();
                        if ("SimpleModel".equals(elementName.getLocalPart())) {
                            if (items == null) {
                                items = new ArrayList<>();
                            }
                            items.add(SimpleModel.fromXml(reader, "SimpleModel"));
                        } else {
                            reader.skipElement();
                        }
                    }
                } else {
                    reader.skipElement();
                }
            }
            return new ModelWithRenamedWrappedModelArray(items);
        });
    }
}
