jobs:
  - job: PublishCliArtifacts
    displayName: Publish artifacts
    pool:
      name: $(LINUXPOOL)
      image: $(LINUXVMIMAGE)
      os: linux

    steps:
      - download: current
        artifact: standalone-macos-signed
        displayName: Download macos binaries

      - download: current
        artifact: standalone-windows-signed
        displayName: Download windows binaries

      - download: current
        artifact: standalone-linux-arm64
        displayName: Download linux arm64 binaries

      - download: current
        artifact: standalone-linux-x64
        displayName: Download linux x64 binaries

      - script: |
          set -e
          mkdir release
          tar -cvzf release/tsp-darwin-arm64.tar.gz -C $(Pipeline.Workspace)/standalone-macos-signed/standalone-macos-arm64 tsp
          tar -cvzf release/tsp-darwin-x64.tar.gz -C $(Pipeline.Workspace)/standalone-macos-signed/standalone-macos-x64 tsp

          tar -cvzf release/tsp-linux-arm64.tar.gz -C $(Pipeline.Workspace)/standalone-linux-arm64 tsp
          tar -cvzf release/tsp-linux-x64.tar.gz -C $(Pipeline.Workspace)/standalone-linux-x64 tsp

          # zip release/tsp-windows-arm64.zip -j $(Pipeline.Workspace)/standalone-windows-signed/standalone-windows-arm64/tsp.exe
          zip release/tsp-windows-x64.zip -j $(Pipeline.Workspace)/standalone-windows-signed/standalone-windows-x64/tsp.exe

          ls ./release
        displayName: Prepare for packaging

      - script: |

        displayName: Get package version
        workingDirectory: $(Build.SourcesDirectory)/packages/standalone
      - task: AzureCLI@1
        displayName: "Upload to storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            PACKAGE_VERSION=$(cat package.json \
              | grep version \
              | head -1 \
              | awk -F: '{ print $2 }' \
              | sed 's/[",]//g')

            echo "Package version is $PACKAGE_VERSION"
            az storage blob upload-batch \
              --auth-mode login \
              --destination dist \
              --account-name "typespec" \
              --destination-path "/$PACKAGE_VERSION/" \
              --source "./release/"
