jobs:
  - job: SignWindows
    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: windows

    steps:
      - download: current
        artifact: standalone-windows-x64
        patterns: tsp.exe
        displayName: Download x64 binary
      - download: current
        artifact: standalone-windows-arm64
        patterns: tsp.exe
        displayName: Download arm64 binary

      - pwsh: |
          New-Item -ItemType Directory -Path windows
          Copy-Item $(Pipeline.Workspace)/standalone-windows-x64/tsp.exe windows/standalone-windows-x64/
          Copy-Item $(Pipeline.Workspace)/standalone-windows-arm64/tsp.exe windows/standalone-windows-arm64/
        displayName: Package windows binary for signing

      - template: /eng/tsp-core/pipelines/templates/signing/windows.yml
        parameters:
          path: windows

      - pwsh: Copy-Item windows/*/tsp signed-windows/ -Recurse
        displayName: Copy to output dir

    templateContext:
      outputs:
        - output: pipelineArtifact
          path: signed-windows
          artifact: standalone-windows-signed
          displayName: Publish signed binaries
