# Job to verify the tsp cli was built/signed correctly

parameters:
  - name: name
    type: string
  - name: pool
    type: string
  - name: vmImage
    type: string
  - name: hostArchitecture
    type: string
    default: ""
  - name: os
    type: string
  - name: artifactName
    type: string
  - name: exePath # Path relative to the artifact root
    type: string

jobs:
  - job: verify_${{ replace(parameters.name, '-', '_') }}
    displayName: Verify ${{ parameters.name }}
    pool:
      name: ${{ parameters.pool }}
      # 1es pipeline templates converts `image` to demands: ImageOverride under the hood
      # which is incompatible with image selection in the default non-1es hosted pools
      ${{ if eq(parameters.os, 'macOS') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ else }}:
        image: ${{ parameters.vmImage }}
      os: ${{ parameters.os }}
      ${{ if eq(parameters.hostArchitecture, 'arm64') }}:
        hostArchitecture: ${{ parameters.hostArchitecture }}

    steps:
      - download: current
        artifact: ${{ parameters.artifactName }}
        displayName: Download binary

      - script: chmod +x $(Pipeline.Workspace)/${{parameters.artifactName}}/${{parameters.exePath}}
        displayName: Set permissions

      - script: $(Pipeline.Workspace)/${{parameters.artifactName}}/${{parameters.exePath}} --help
        displayName: Verify binary
