# Job to verify the tsp cli was built/signed correctly

parameters:
  - name: platform
    type: string
  - name: artifactName
    type: string
  - name: exePath # Path relative to the artifact root
    type: string

jobs:
  - job: verify_${{ replace(parameters.platform, '-', '_') }}
    displayName: Verify ${{ parameters.platform }}
    pool:
      ${{ if eq(parameters.os, 'linux-x64') }}:
        name: $(LINUXPOOL)
        image: $(LINUXVMIMAGE)
        os: linux
      ${{ else if eq(parameters.os, 'linux-arm64') }}:
        name: $(LINUXARMPOOL)
        image: $(LINUXARMVMIMAGE)
        os: linux
        hostArchitecture: arm64
      ${{ else if eq(parameters.os, 'macos-x64') }}:
        name: $(MACPOOL)
        vmImage: $(MACVMIMAGE)
        os: macOS
      ${{ else if eq(parameters.os, 'macos-arm64') }}:
        name: $(MACPOOL)
        vmImage: $(MACVMIMAGEM1)
        os: macOS
      ${{ else if eq(parameters.os, 'windows-x64') }}:
        name: $(WINDOWSPOOL)
        image: $(WINDOWSVMIMAGE)
        os: windows
      ${{ else if eq(parameters.os, 'windows-arm64') }}:
        name: $(ARMPOOL)
        image: $(WINDOWSARMVMIMAGE)
        os: windows

    steps:
      - download: current
        artifact: ${{ parameters.artifactName }}
        displayName: Download binary

      - script: chmod +x $(Pipeline.Workspace)/${{parameters.artifactName}}/${{parameters.exePath}}
        displayName: Set permissions

      - script: $(Pipeline.Workspace)/${{parameters.artifactName}}/${{parameters.exePath}} --help
        displayName: Verify binary
