packages:
  - packages/*
  - e2e
  - website
  - "!packages/http-client-csharp/**"
  - "!packages/http-client-java/**"
  - "!packages/http-client-python/**"

catalog:
  "@alloy-js/cli": ^0.22.0
  "@alloy-js/core": ^0.22.0
  "@alloy-js/csharp": ^0.22.0
  "@alloy-js/markdown": ^0.22.0
  "@alloy-js/python": ^0.3.0
  "@alloy-js/rollup-plugin": ^0.1.0
  "@alloy-js/typescript": ^0.22.0
  "@astrojs/check": ^0.9.7
  "@astrojs/react": ^5.0.0
  "@astrojs/starlight": ^0.38.1
  "@azure/identity": ~4.13.0
  "@azure/storage-blob": ~12.31.0
  "@babel/code-frame": ~7.29.0
  "@babel/core": ^7.29.0
  "@chronus/chronus": ^1.3.1
  "@chronus/github": ^1.0.6
  "@chronus/github-pr-commenter": ^1.0.6
  "@docsearch/css": ^4.6.0
  "@docsearch/js": ^4.6.0
  "@eslint/js": ^10.0.1
  "@expressive-code/core": ^0.41.7
  "@fluentui/react-components": ~9.73.3
  "@fluentui/react-icons": ^2.0.323
  "@fluentui/react-list": ^9.6.12
  "@inquirer/prompts": ^8.3.0
  "@microsoft/api-extractor": ^7.57.7
  "@microsoft/api-extractor-model": ^7.33.4
  "@microsoft/tsdoc": ^0.16.0
  "@microsoft/tsdoc-config": ^0.18.1
  "@octokit/core": ^7.0.6
  "@octokit/plugin-paginate-graphql": ^6.0.0
  "@octokit/plugin-rest-endpoint-methods": ^17.0.0
  "@playwright/test": ^1.58.2
  "@pnpm/workspace.find-packages": ^1000.0.64
  "@scalar/json-magic": ^0.11.5
  "@scalar/openapi-parser": ^0.24.1
  "@scalar/openapi-types": ^0.5.0
  "@storybook/cli": ^10.3.3
  "@storybook/react-vite": ^10.3.3
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.9.1
  "@testing-library/react": ^16.3.2
  "@types/babel__code-frame": ~7.27.0
  "@types/cross-spawn": ~6.0.6
  "@types/debounce": ~1.2.4
  "@types/express": ^5.0.6
  "@types/micromatch": ^4.0.10
  "@types/morgan": ^1.9.10
  "@types/multer": ^2.1.0
  "@types/mustache": ~4.2.6
  "@types/node": ~25.5.0
  "@types/plist": ~3.0.5
  "@types/react": ~19.2.14
  "@types/react-dom": ~19.2.3
  "@types/remark-heading-id": ^1.0.0
  "@types/semver": ^7.7.1
  "@types/swagger-ui": ~5.32.0
  "@types/swagger-ui-dist": ~3.30.6
  "@types/swagger-ui-express": ^4.1.8
  "@types/which": ^3.0.4
  fast-xml-parser: ^5.5.9
  "@types/yargs": ~17.0.35
  "@typescript-eslint/parser": ^8.57.0
  "@typescript-eslint/rule-tester": ^8.57.0
  "@typescript-eslint/types": ^8.57.0
  "@typescript-eslint/utils": ^8.57.0
  "@typespec/ts-http-runtime": 0.3.4
  "@vitejs/plugin-react": ~6.0.1
  "@vitest/coverage-v8": ^4.1.0
  "@vitest/eslint-plugin": ^1.6.12
  "@vitest/ui": ^4.1.0
  "@vscode/extension-telemetry": ^1.5.1
  "@vscode/test-electron": ^2.5.2
  "@vscode/test-web": ^0.0.80
  "@vscode/vsce": ~3.7.1
  "@yarnpkg/core": ^4.6.0
  "@yarnpkg/fslib": ^3.1.4
  "@yarnpkg/plugin-nm": ^4.0.8
  "@yarnpkg/plugin-npm": ^3.4.0
  "@yarnpkg/plugin-pnp": ^4.1.3
  ajv: ~8.18.0
  ajv-formats: ~3.0.1
  astro: ^6.0.4
  astro-expressive-code: ^0.41.7
  astro-rehype-relative-markdown-links: ^0.18.1
  c8: ^11.0.0
  change-case: ~5.4.4
  chokidar: ~5.0.0
  clsx: ^2.1.1
  concurrently: ^9.2.1
  cross-env: ~10.1.0
  cross-spawn: ^7.0.6
  cspell: ^9.7.0
  debounce: ~3.0.0
  decimal.js: ^10.6.0
  ecmarkup: ~23.0.2
  env-paths: ^4.0.0
  es-module-shims: ~2.8.0
  esbuild: ^0.27.4
  esbuild-plugins-node-modules-polyfill: ^1.8.1
  eslint: ^10.0.3
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-unicorn: ^63.0.0
  execa: ^9.6.1
  express: ^5.2.1
  globby: ~16.1.1
  happy-dom: ^20.8.9
  is-unicode-supported: ^2.1.0
  log-symbols: ^7.0.1
  lzutf8: 0.6.3
  micromatch: ^4.0.8
  monaco-editor: ~0.55.1
  monaco-editor-core: ^0.55.1
  morgan: ^1.10.1
  multer: ^2.1.1
  mustache: ~4.2.0
  ora: ^9.3.0
  p-limit: ^7.3.0
  pathe: ^2.0.3
  picocolors: ~1.1.1
  playwright: ^1.58.2
  plist: ~3.1.0
  postject: 1.0.0-alpha.6
  prettier: ~3.8.1
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-organize-imports: ~4.3.0
  prettier-plugin-sh: ^0.18.0
  prism-react-renderer: ^2.4.1
  react: ~19.2.4
  react-dom: ~19.2.4
  react-error-boundary: ^6.1.1
  react-hotkeys-hook: ^5.2.4
  react-markdown: ^10.1.0
  rehype-mermaid: ^3.0.0
  remark-heading-id: ^1.0.1
  rimraf: ~6.1.3
  rollup-plugin-visualizer: 6.0.4
  semver: ^7.7.4
  sharp: ^0.34.5
  simple-git: ^3.33.0
  source-map-support: ~0.5.21
  storybook: ^10.3.3
  strip-json-comments: ~5.0.3
  swagger-ui-dist: ^5.32.0
  swagger-ui-express: ^5.0.1
  tar: ^7.5.11
  temporal-polyfill: ^0.3.2
  tree-sitter-c-sharp: ^0.23.1
  tree-sitter-java: ^0.23.5
  tree-sitter-javascript: ^0.25.0
  tree-sitter-python: ^0.25.0
  tree-sitter-typescript: ^0.23.2
  tsx: ^4.21.0
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  typescript: ~5.9.3
  typescript-eslint: ^8.57.0
  uri-template: ^2.0.0
  vite: ^8.0.1
  vite-plugin-checker: ^0.12.0
  vite-plugin-dts: 4.5.4
  vitest: ^4.1.0
  vscode-languageclient: ~9.0.1
  vscode-languageserver: ~9.0.1
  vscode-languageserver-textdocument: ~1.0.12
  vscode-oniguruma: ~2.0.1
  vscode-textmate: ~9.3.2
  web-tree-sitter: ^0.26.7
  which: ^6.0.1
  yaml: ~2.8.2
  yargs: ~18.0.0

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@alloy-js/*"

overrides:
  dompurify: ^3.3.3 # Monaco editor pinned to 3.2.7 https://github.com/microsoft/monaco-editor/issues/5248
  cross-spawn@>=7.0.0 <7.0.5: ">=7.0.5"
  diff@>=6.0.0 <8.0.3: ">=8.0.3"
  yaml@>=2.0.0 <2.8.3: ">=2.8.3"
