emit:
  - "@typespec/http-client-java"
options:
  "@typespec/http-client-java":
    emitter-output-dir: "{project-root}/tsp-output"
    partial-update: true
    generate-samples: true
    generate-tests: true
    examples-dir: "{project-root}/tsp/examples"
    flavor: "Azure"
#    customization-class: ../customization/src/main/java/KeyVaultCustomization.java
    dev-options:
      generate-code-model: true
      loglevel: info
      debug: true
      profile: false
