timeout: 60_000
require: source-map-support/register.js
spec: "test/**/*.{test,e2e}.ts"

# Config for https://www.npmjs.com/package/mocha-multi-reporters
reporterOptions: "configFile=mocha.reporter.config.json"
node-option: loader=ts-node/esm
