// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armresourceprovider.models;

import com.azure.core.util.Context;

/**
 * Resource collection API of LroNoBodies.
 */
public interface LroNoBodies {
    /**
     * Create a ResourceLroNoBody.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param resourceLroNoBodyName The name of the ResourceLroNoBody.
     * @param resource Resource create parameters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    ResourceLroNoBody createOrUpdate(String resourceGroupName, String resourceLroNoBodyName,
        ResourceLroNoBody resource);

    /**
     * Create a ResourceLroNoBody.
     * 
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param resourceLroNoBodyName The name of the ResourceLroNoBody.
     * @param resource Resource create parameters.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws com.azure.core.management.exception.ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    ResourceLroNoBody createOrUpdate(String resourceGroupName, String resourceLroNoBodyName, ResourceLroNoBody resource,
        Context context);
}
