parameters:
  - name: Condition
    type: string
    default: true
  - name: DependsOn
    type: object
    default: []

stages:
  - stage: vscode_extension_UI_Test
    displayName: "VSCode Extension - UI Test"
    pool:
      name: $(WINDOWSPOOL)
      image: $(WINDOWSVMIMAGE)
      os: windows
    jobs:
      - job: UI_Test
        displayName: "UI Test"
        steps:
          - template: /eng/tsp-core/pipelines/templates/install.yml
          - template: /eng/tsp-core/pipelines/templates/build.yml
