// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.multipleclientssameversion;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import tsptest.multipleclientssameversion.implementation.AlphaClientImpl;
import tsptest.multipleclientssameversion.models.Resource;

/**
 * Initializes a new instance of the synchronous AlphaClient type.
 */
@ServiceClient(builder = AlphaClientBuilder.class)
public final class AlphaClient {
    @Generated
    private final AlphaClientImpl serviceClient;

    /**
     * Initializes an instance of AlphaClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    AlphaClient(AlphaClientImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The getAlpha operation.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     id: String (Required)
     *     name: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param id The id parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getAlphaWithResponse(String id, RequestOptions requestOptions) {
        return this.serviceClient.getAlphaWithResponse(id, requestOptions);
    }

    /**
     * The getAlpha operation.
     * 
     * @param id The id parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Resource getAlpha(String id) {
        // Generated convenience method for getAlphaWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getAlphaWithResponse(id, requestOptions).getValue().toObject(Resource.class);
    }
}
