// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.clientgenerator.core.apiversion.path;

import com.azure.core.util.ServiceVersion;

/**
 * Service version of PathClient.
 */
public enum PathServiceVersion implements ServiceVersion {
    /**
     * Enum value 2025-01-01.
     */
    V2025_01_01("2025-01-01");

    private final String version;

    PathServiceVersion(String version) {
        this.version = version;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     * 
     * @return The latest {@link PathServiceVersion}.
     */
    public static PathServiceVersion getLatest() {
        return V2025_01_01;
    }
}
