// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.armresourceprovider.implementation.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.cadl.armresourceprovider.fluent.models.ChildExtensionResourceInner;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The response of a ChildExtensionResource list operation.
 */
@Immutable
public final class ChildExtensionResourceListResult {
    /*
     * The ChildExtensionResource items on this page
     */
    @JsonProperty(value = "value", required = true)
    private List<ChildExtensionResourceInner> value;

    /*
     * The link to the next page of items
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Creates an instance of ChildExtensionResourceListResult class.
     */
    private ChildExtensionResourceListResult() {
    }

    /**
     * Get the value property: The ChildExtensionResource items on this page.
     * 
     * @return the value value.
     */
    public List<ChildExtensionResourceInner> value() {
        return this.value;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (value() == null) {
            throw LOGGER.atError()
                .log(new IllegalArgumentException(
                    "Missing required property value in model ChildExtensionResourceListResult"));
        } else {
            value().forEach(e -> e.validate());
        }
    }

    private static final ClientLogger LOGGER = new ClientLogger(ChildExtensionResourceListResult.class);
}
