// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.models.resources.implementation;

import com.azure.core.management.SystemData;
import com.azure.resourcemanager.models.resources.fluent.models.SingletonTrackedResourceInner;
import com.azure.resourcemanager.models.resources.models.SingletonTrackedResource;
import com.azure.resourcemanager.models.resources.models.SingletonTrackedResourceProperties;
import java.util.Collections;
import java.util.Map;

public final class SingletonTrackedResourceImpl implements SingletonTrackedResource {
    private SingletonTrackedResourceInner innerObject;

    private final com.azure.resourcemanager.models.resources.ResourcesManager serviceManager;

    SingletonTrackedResourceImpl(SingletonTrackedResourceInner innerObject,
        com.azure.resourcemanager.models.resources.ResourcesManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public String location() {
        return this.innerModel().location();
    }

    public Map<String, String> tags() {
        Map<String, String> inner = this.innerModel().tags();
        if (inner != null) {
            return Collections.unmodifiableMap(inner);
        } else {
            return Collections.emptyMap();
        }
    }

    public SingletonTrackedResourceProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public SingletonTrackedResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.models.resources.ResourcesManager manager() {
        return this.serviceManager;
    }
}
