// export {
//   ArrayBuilder,
//   CircularEmit,
//   CodeTypeEmitter,
//   Declaration,
//   EmitterResult,
//   NoEmit,
//   ObjectBuilder,
//   Placeholder,
//   RawCode,
//   ReferenceCycle,
//   StringBuilder,
//   TypeEmitter,
//   code,
//   createAssetEmitter,
//   type AssetEmitter,
//   type AssetTag,
//   type AssetTagFactory,
//   type AssetTagInstance,
//   type Context,
//   type ContextState,
//   type ESRecord,
//   type EmitEntity,
//   type EmitTypeReferenceOptions,
//   type EmittedSourceFile,
//   type EmitterOutput,
//   type EmitterState,
//   type LexicalTypeStackEntry,
//   type NamespaceScope,
//   type Scope,
//   type ScopeBase,
//   type SourceFile,
//   type SourceFileScope,
//   type TypeEmitterMethod,
//   type TypeReference,
//   type TypeSpecDeclaration,
// } from "@typespec/asset-emitter";

// TODO: figure out what to do here
