parameters:
  - name: Condition
    type: string
    default: true
  - name: DependsOn
    type: object
    default: []

stages:
  - template: /eng/emitters/pipelines/templates/stages/emitter-stages.yml
    parameters:
      StagePrefix: CSharp
      BuildPrereleaseVersion: true
      UseTypeSpecNext: false
      Publish: "none"
      PackagePath: /packages/http-client-csharp
      EmitterPackageJsonPath: packages/http-client-csharp/package.json
      Packages:
        - name: typespec-http-client-csharp
          file: typespec-http-client-csharp-*.tgz
          type: npm
        - name: Microsoft.TypeSpec.Generator
          file: Microsoft.TypeSpec.Generator.*.nupkg
          type: nuget
        - name: Microsoft.TypeSpec.Generator.ClientModel
          file: Microsoft.TypeSpec.Generator.ClientModel.*.nupkg
          type: nuget
        - name: Microsoft.TypeSpec.Generator.Input
          file: Microsoft.TypeSpec.Generator.Input.*.nupkg
          type: nuget
        - name: Microsoft.TypeSpec.Generator.Customization
          file: Microsoft.TypeSpec.Generator.Customization.*.nupkg
          type: nuget
      UnitTestArgs: -UnitTests
      TestMatrix:
        RegenCheck:
          TestArguments: -GenerationChecks
      Condition: ${{ parameters.Condition }}
      DependsOn: ${{ parameters.DependsOn }}
      LanguageShortName: "csharp"
