// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for BooleanModel.
 * Test for encode decorator on boolean.
 * <!-- end generated doc -->
 */
package encode.booleannamespace;
