// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the service clients for ServiceGroupExtension.
 * Arm Resource Provider service group API.
 */
package azure.resourcemanager.servicegroupextension.fluent;
