# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main.proto", :syntax => :proto3) do
    add_message "Input" do
      optional :testInputField, :string, 1
      optional :type, :enum, 2, "InputType"
      optional :aliased, :enum, 3, "InputTypeWithAlias"
    end
    add_message "Output" do
      optional :testOutputField, :int32, 1
      optional :secondField, :string, 2
    end
    add_enum "InputType" do
      value :FOO, 0
      value :BAR, 1
    end
    add_enum "InputTypeWithAlias" do
      value :BAZ, 0
      value :QUX, 1
      value :FUZ, 1
    end
  end
end

Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Input").msgclass
Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Output").msgclass
InputType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InputType").enummodule
InputTypeWithAlias = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InputTypeWithAlias").enummodule
