// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the implementations for NotDiscriminated.
 * Illustrates not-discriminated inheritance model.
 */
package type.model.inheritance.notdiscriminated.implementation;
