// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
/**
 * <!-- start generated doc -->
 * Package containing the data models for PartialUpdate.
 * <!-- end generated doc -->
 */
package com.cadl.partialupdate.models;
