// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the data models for Pageable.
 * Test for pageable payload.
 */
package payload.pageable.serverdrivenpagination.continuationtoken.implementation;
