// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.enumservice.models;

/**
 * Defines values for OperationName.
 */
public enum OperationName {
    /**
     * Enum value Read.
     */
    READ("Read"),

    /**
     * Enum value Write.
     */
    WRITE("Write");

    /**
     * The actual serialized value for a OperationName instance.
     */
    private final String value;

    OperationName(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a OperationName instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed OperationName object, or null if unable to parse.
     */
    public static OperationName fromString(String value) {
        if (value == null) {
            return null;
        }
        OperationName[] items = OperationName.values();
        for (OperationName item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
