// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.payload.contentnegotiation.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The PngImageAsJson model.
 */
@Immutable
public final class PngImageAsJson implements JsonSerializable<PngImageAsJson> {
    /*
     * The content property.
     */
    @Generated
    private final byte[] content;

    /**
     * Creates an instance of PngImageAsJson class.
     * 
     * @param content the content value to set.
     */
    @Generated
    private PngImageAsJson(byte[] content) {
        this.content = content;
    }

    /**
     * Get the content property: The content property.
     * 
     * @return the content value.
     */
    @Generated
    public byte[] getContent() {
        return CoreUtils.clone(this.content);
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeBinaryField("content", this.content);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PngImageAsJson from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PngImageAsJson if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PngImageAsJson.
     */
    @Generated
    public static PngImageAsJson fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            byte[] content = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("content".equals(fieldName)) {
                    content = reader.getBinary();
                } else {
                    reader.skipChildren();
                }
            }
            return new PngImageAsJson(content);
        });
    }
}
