jobs:
  - job: build
    displayName: Build Packages

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: /eng/tsp-core/pipelines/templates/install.yml
        parameters:
          useDotNet: true

      - script: pnpm run update-telemetry-key $(vscode.telemetryKey)
        workingDirectory: $(Build.SourcesDirectory)/packages/typespec-vscode
        displayName: Update vscode telemetry key

      - template: /eng/tsp-core/pipelines/templates/build.yml

      # - script: pnpm run test:ci
      #   displayName: Test

      - template: /eng/tsp-core/pipelines/templates/upload-coverage.yml
      - template: /eng/tsp-core/pipelines/templates/pack.yml
        parameters:
          artifactName: npm-packages-stable
          name: npm_packages_stable

      - task: CopyFiles@2
        displayName: "Copy VSCode extension .vsix to artifact directory"
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/typespec-vscode"
          Contents: "*.vsix"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/vscode-extension"

      - task: CopyFiles@2
        displayName: "Copy VS extension .vsix to artifact directory"
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)/packages/typespec-vs"
          Contents: "*.vsix"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/vs-extension"

      - task: AzureCLI@1
        displayName: "Publish bundled packages to package storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: node ./eng/tsp-core/scripts/upload-bundler-packages.js

      - pwsh: |
          $publishSummary = Get-Content "$(Build.ArtifactStagingDirectory)/npm-packages-stable/publish-summary.json" | ConvertFrom-Json
          if ($publishSummary.packages.'@typespec/http-specs'.published -eq $true) {
            Write-Output "Setting PublishHttpSpecs variable to true."
            Write-Host "##vso[task.setvariable variable=PublishHttpSpecs]true"
          } else {
            Write-Output "Setting PublishHttpSpecs variable to false."
            Write-Host "##vso[task.setvariable variable=PublishHttpSpecs]false"
          }
        displayName: "Check if @typespec/http-specs was published"

      - task: AzureCLI@2
        displayName: Upload scenario manifest
        condition: eq(variables['PublishHttpSpecs'], 'true')
        inputs:
          workingDirectory: packages/http-specs
          azureSubscription: "TypeSpec Storage"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: "pnpm upload-manifest"

      # Update version for next version publish
      - script: node ./packages/internal-build-utils/cmd/cli.js bump-version-preview .
        displayName: Bump version to prerelease targets

      - script: pnpm run gen-manifest
        displayName: Regen manifest for compiler
        workingDirectory: ./packages/compiler

      - template: /eng/tsp-core/pipelines/templates/pack.yml
        parameters:
          artifactName: npm-packages-next
          name: npm_packages_next

      # Publish Next playground
      - task: AzureCLI@1
        displayName: "Publish playground"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch ^
              --auth-mode login ^
              --destination $web ^
              --account-name "cadlplayground" ^
              --destination-path / ^
              --source "./packages/playground-website/dist/web/" ^
              --overwrite

    templateContext:
      # Optimize so each output doesn't create its own scan
      # https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs#multiple-outputs
      outputParentDirectory: $(Build.ArtifactStagingDirectory)
      outputs:
        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/npm-packages-stable
          artifact: npm-packages-stable
          displayName: Publish npm stable packages(.tgz) as pipeline artifacts

        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/npm-packages-next
          artifact: npm-packages-next
          displayName: Publish npm next packages(.tgz) as pipeline artifacts

        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/vscode-extension
          artifact: vscode-extension-unsigned
          displayName: Publish VSCode extension(.vsix) as pipeline artifacts

        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/vs-extension
          artifact: vs-extension-unsigned
          displayName: Publish VS extension(.vsix) as pipeline artifacts
