parameters:
  - name: azLogin
    type: boolean
    default: false
jobs:
  - job: e2e
    displayName: E2E Tests

    variables:
      TYPESPEC_VS_CI_BUILD: false # Enable official Visual Studio extension build
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build
      DISPLAY: ":99" # Set DISPLAY for Linux GUI applications

    pool:
      name: $(LINUXPOOL)
      image: $(LINUXVMIMAGE)
      os: linux

    steps:
      - template: /eng/tsp-core/pipelines/templates/install.yml
      - template: /eng/tsp-core/pipelines/templates/install-browsers.yml
      - template: /eng/tsp-core/pipelines/templates/setup-linux-ui.yml
      - template: /eng/tsp-core/pipelines/templates/build.yml

      - ${{ if parameters.azLogin }}:
          - task: AzureCLI@1
            displayName: E2E Tests
            inputs:
              azureSubscription: "Azure SDK Engineering System"
              scriptLocation: inlineScript
              inlineScript: pnpm run test:e2e
      - ${{ else }}:
          - script: pnpm run test:e2e
            displayName: E2E Tests

      - task: 1ES.PublishPipelineArtifact@1
        inputs:
          path: ./packages/playground-website/test-results
          artifact: "uitestresults-e2e"
        displayName: Publish UI tests artifacts
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: 1ES.PublishPipelineArtifact@1
        inputs:
          path: ./packages/typespec-vscode/temp/images-linux
          artifact: "screenshots"
        displayName: Publish screenshots
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - task: 1ES.PublishPipelineArtifact@1
        inputs:
          path: ./packages/typespec-vscode/test-results
          artifact: "trace-results"
        displayName: Publish trace results
        condition: ne(variables['Agent.OS'], 'Windows_NT')

      - script: node eng/common/scripts/check-for-changed-files.js
        displayName: Check Git Status For Changed Files
