parameters:
  - name: artifactName
    type: string
  - name: tag
    type: string
  - name: condition
    default: succeeded()
  - name: dependsOn
    type: string
    default: ""

jobs:
  - deployment: publish_npm_${{ parameters.tag }}
    displayName: Publish Npm (${{ parameters.tag }})
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    environment: package-publish
    pool: # hardcoding the pool and image name because deployment jobs do not support variable expansion in pool names
      name: azsdk-pool
      image: ubuntu-24.04
      os: linux
    templateContext:
      type: releaseJob
      isProduction: true
      inputs:
        - input: pipelineArtifact
          artifactName: ${{ parameters.artifactName }}
          itemPattern: "**/*.{tgz}"
          targetPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/

    strategy:
      runOnce:
        deploy:
          steps:
            - script: ls $(Pipeline.Workspace)/${{ parameters.artifactName }}
              displayName: List files in artifact

            - template: /eng/tsp-core/pipelines/templates/release/esrp-release.yml
              parameters:
                tag: ${{ parameters.tag }}
                path: "$(Pipeline.Workspace)/${{ parameters.artifactName }}"

            - script: |
                echo "ESRP_RELEASE_DETAILS:"
                echo "$ESRP_RELEASE_DETAILS"
              displayName: "Log ESRP release details"
