parameters:
  - name: jobName
    type: string
  - name: name
    type: string
  - name: pool
    type: string
  - name: vmImage
    type: string
  - name: os
    type: string

jobs:
  - job: single_exe_${{ parameters.jobName }}
    displayName: Build single exe ${{ parameters.name }}
    pool:
      name: ${{ parameters.pool }}
      image: ${{ parameters.vmImage }}
      os: ${{ parameters.os }}

    steps:
      - template: /eng/tsp-core/pipelines/templates/install.yml
        parameters:
          nodeVersion: 22.x

      - script: pnpm build
        workingDirectory: packages/standalone
        displayName: Build

    templateContext:
      outputs:
        - output: pipelineArtifact
          path: $(Build.ArtifactStagingDirectory)/packages/standalone/dist
          artifact: standalone-${{ parameters.name }}
          displayName: Publish standalone dist as pipeline artifacts
