parameters:
  ArtifactPath: $(System.DefaultWorkingDirectory)
  Artifacts: []
  ArtifactName: "packages"
  LanguageShortName: "Unknown"

jobs:
  - job: DetectApiChanges
    dependsOn: Build_linux_20
    pool:
      name: $(LINUXPOOL)
      image: $(LINUXVMIMAGE)
      os: linux
    steps:
      - download: current
        artifact: build_artifacts
        displayName: Download build artifacts
      - pwsh: |
          $apiChangeDetectRequestUrl = "https://apiview.dev/PullRequest/DetectApiChanges"
          echo "##vso[task.setvariable variable=ApiChangeDetectRequestUrl]$apiChangeDetectRequestUrl"
        displayName: "Set API change detect request URL"
        condition: eq(variables['ApiChangeDetectRequestUrl'], '')

      - task: Powershell@2
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/emitters/scripts/Detect-Api-Changes.ps1
          arguments: >
            -ArtifactList ('${{ convertToJson(parameters.Artifacts) }}' | ConvertFrom-Json | Select-Object Name)
            -ArtifactPath ${{parameters.ArtifactPath}}/build_artifacts/${{parameters.LanguageShortName}}/packages
            -CommitSha '$(Build.SourceVersion)'
            -BuildId $(Build.BuildId)
            -PullRequestNumber $(System.PullRequest.PullRequestNumber)
            -RepoFullName $(Build.Repository.Name)
            -APIViewUri $(ApiChangeDetectRequestUrl)
            -ArtifactName ${{ parameters.ArtifactName }}
            -DevopsProject $(System.TeamProject)
            -LanguageShortName ${{ parameters.LanguageShortName }}
          pwsh: true
        displayName: Detect API changes
        condition: and(succeededOrFailed(), eq(variables['Build.Reason'],'PullRequest'))
