parameters:
  # Custom steps to run in the Build and Test stages after the repositories are cloned.
  - name: AdditionalInitializeSteps
    type: stepList
    default: []

  # Location of emitter package path
  - name: PackagePath
    type: string

  # Arguments needed to run tests
  - name: TestArgs
    type: string
    default: ""

  # Indicates the build matrix to use for post-build autorest validation
  - name: TestMatrix
    type: object
    default: {}

  # Node version
  - name: NodeVersion
    type: string
    default: "20.x"

  # Operation system to use
  - name: Os
    type: string

  # Emit artifacts
  - name: EmitArtifacts
    type: boolean
    default: false

jobs:
  - job: Test_${{ parameters.Os }}_${{ split(parameters.NodeVersion, '.')[0] }}
    ${{ if eq(parameters.Os, 'linux') }}:
      pool:
        name: $(LINUXPOOL)
        image: $(LINUXVMIMAGE)
        os: linux
    ${{ else }}:
      pool:
        name: $(WINDOWSPOOL)
        image: $(WINDOWSVMIMAGE)
        os: windows
    ${{ if ne(length(parameters.TestMatrix), 0) }}:
      strategy:
        matrix: ${{ parameters.TestMatrix }}
    steps:
      - template: /eng/emitters/pipelines/templates/steps/test-step.yml
        parameters:
          AdditionalInitializeSteps: ${{ parameters.AdditionalInitializeSteps }}
          PackagePath: ${{ parameters.PackagePath }}
          NodeVersion: $(nodeVersion)
          ${{ if ne(length(parameters.TestMatrix), 0) }}:
            TestArgs: $(TestArguments)
          ${{ else }}:
            TestArgs: ${{ parameters.TestArgs }}
    ${{ if parameters.EmitArtifacts }}:
      templateContext:
        outputs:
          - output: pipelineArtifact
            path: $(Build.ArtifactStagingDirectory)
            artifact: test_artifacts_$(System.JobName)
