stages:
  - stage: sign_tsp_cli
    displayName: Sign tsp cli binaries
    dependsOn: build_tsp_cli

    jobs:
      - template: /eng/tsp-core/pipelines/jobs/cli/sign-macos.yml
      - template: /eng/tsp-core/pipelines/jobs/cli/sign-windows.yml
