stages:
  - stage: sign_tsp_cli
    displayName: Sign tsp cli binaries
    dependsOn: build_tsp_cli

    jobs:
      - job: SignMac
        pool:
          name: $(WINDOWSPOOL)
          image: $(WINDOWSVMIMAGE)
          os: windows

        steps:
          - download: current
            artifact: standalone-macos-x64
            patterns: tsp
            path: artifacts
            displayName: Download macos x64 binary
          - download: current
            artifact: standalone-macos-arm64
            patterns: tsp
            path: artifacts
            displayName: Download macos arm64 binary

          - pwsh: |
              New-Item -ItemType Directory -Path macos

              Compress-Archive `
                -Path artifacts/standalone-macos-x64 `
                -DestinationPath macos/standalone-macos-x64.zip

              Compress-Archive `
                -Path artifacts/standalone-macos-arm64 `
                -DestinationPath macos/standalone-macos-arm64.zip
            displayName: Package mac binary for signing

          - template: /eng/tsp-core/pipelines/templates/signing/macos.yml
            parameters:
              path:

          - pwsh: |
              Expand-Archive -Path macos/standalone-macos-x64.zip -DestinationPath macos/
              Expand-Archive -Path macos/standalone-macos-x64.zip -DestinationPath macos/

              Remove-Item macos/standalone-macos-x64.zip
              Remove-Item macos/standalone-macos-x64.zip
            displayName: Extract signed binaries

          - pwsh: |
              New-Item -ItemType Directory -Path signed-mac
              Copy-Item macos/* signed-macos/ -Recurse
            displayName: Copy signing outputs
            condition: always()

        templateContext:
          outputs:
            - output: pipelineArtifact
              path: signed-macos
              artifact: signed-macos
              displayName: Publish signed macOS binaries
