stages:
  - stage: build_tsp_cli
    displayName: Build Tsp CLI
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
    jobs:
      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          name: linux-x64
          pool: $(LINUXPOOL)
          vmImage: $(LINUXVMIMAGE)
          os: linux

      # TODO:
      ##[error]Error running credscan job: 1 of 1
      ##[error]ToolLauncherNotFoundException: Could not successfully find the /mnt/vss/_work/_gdn/packages/nuget/Microsoft.Security.CredScan.Client.linux-x64.2.3.12.23/lib/net6.0/CredentialScanner tool launcher. Please ensure any dependent frameworks are installed.
      ##[error]Win32Exception: An error occurred trying to start process '/mnt/vss/_work/_gdn/packages/nuget/Microsoft.Security.CredScan.Client.linux-x64.2.3.12.23/lib/net6.0/CredentialScanner' with working directory '/mnt/vss/_work/1'. Exec format error

      # - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
      #   parameters:
      #     name: linux-arm64
      #     pool: $(LINUXARMPOOL)
      #     vmImage: $(LINUXARMVMIMAGE)
      #     os: linux

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          name: macos-x64
          pool: $(MACPOOL)
          vmImage: $(MACVMIMAGE)
          os: macOS

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          name: macos-arm64
          pool: $(MACPOOL)
          vmImage: $(MACVMIMAGEM1)
          os: macOS

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          name: windows-x64
          pool: $(WINDOWSPOOL)
          vmImage: $(WINDOWSVMIMAGE)
          os: windows

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          name: windows-arm64
          pool: $(ARMPOOL)
          vmImage: $(WINDOWSARMVMIMAGE)
          os: windows
