stages:
  - stage: Build_SingleExe
    displayName: Core - Build Single Exe
    dependsOn: InitStage
    condition: eq('true', stageDependencies.InitStage.outputs['InitJob.InitStep.RunCore'])
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
    jobs:
      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: linux_x64
          name: linux-x64
          pool: $(LINUXPOOL)
          vmImage: $(LINUXVMIMAGE)
          os: $(LINUXOS)

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: linux_arm64
          name: linux-arm64
          pool: $(LINUXARMPOOL)
          vmImage: $(LINUXARMVMIMAGE)
          os: $(LINUXOS)

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: macos_x64
          name: macos-x64
          pool: $(MACPOOL)
          vmImage: $(MACVMIMAGE)
          os: $(MACOS)

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: macos_arm64
          name: macos-arm64
          pool: $(MACPOOL)
          vmImage: $(MACVMIMAGEM1)
          os: $(MACOS)

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: windows_x64
          name: windows-x64
          pool: $(WINDOWSPOOL)
          vmImage: $(MACVMIMAGE)
          os: $(WINDOWSOS)

      - template: /eng/tsp-core/pipelines/jobs/single-exe.yml
        parameters:
          jobName: windows_arm64
          name: windows-arm64
          pool: $(ARMPOOL)
          vmImage: $(WINDOWSARMVMIMAGE)
          os: $(WINDOWSOS)
