stages:
  - stage: build_tsp_cli
    displayName: Build Tsp CLI
    variables:
      - template: /eng/tsp-core/pipelines/templates/variables/globals.yml@self
    jobs:
      - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
        parameters:
          platform: linux-x64

      - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
        parameters:
          platform: linux-arm64

      - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
        parameters:
          platform: macos-x64

      - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
        parameters:
          platform: macos-arm64

      - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
        parameters:
          platform: windows-x64

      # - template: /eng/tsp-core/pipelines/jobs/cli/verify-tsp-cli.yml
      #   parameters:
      #     platform: windows-arm64
