export { resolveCompilerOptions, ResolveCompilerOptionsOptions } from "./config/index.js";
export * from "./core/index.js";
export * as TypeSpecPrettierPlugin from "./formatter/index.js";
export {
  $defaultVisibility,
  $discriminator,
  $doc,
  $encode,
  $encodedName,
  $error,
  $errorsDoc,
  $example,
  $format,
  $friendlyName,
  $inspectType,
  $inspectTypeName,
  $invisible,
  $key,
  $maxItems,
  $maxLength,
  $maxValue,
  $maxValueExclusive,
  $minItems,
  $minLength,
  $minValue,
  $minValueExclusive,
  $opExample,
  $overload,
  $parameterVisibility,
  $pattern,
  $removeVisibility,
  $returnsDoc,
  $returnTypeVisibility,
  $secret,
  $service,
  $summary,
  $tag,
  $visibility,
  $withDefaultKeyVisibility,
  $withLifecycleUpdate,
  $withOptionalProperties,
  $withoutDefaultValues,
  $withoutOmittedProperties,
  $withPickedProperties,
  $withUpdateableProperties,
  $withVisibility,
  $withVisibilityFilter,
  addService,
  discriminatedDecorator,
  EmptyVisibilityProvider,
  getAllTags,
  getDeprecated,
  getDoc,
  getEncode,
  getErrorsDoc,
  getErrorsDocData,
  getExamples,
  getFormat,
  getFriendlyName,
  getKeyName,
  getOpExamples,
  getOverloadedOperation,
  getOverloads,
  getPagingOperation,
  getParameterVisibilityFilter,
  getPattern,
  getPatternData,
  getReturnsDoc,
  getReturnsDocData,
  getReturnTypeVisibilityFilter,
  getService,
  getSummary,
  getTags,
  isErrorModel,
  isKey,
  isList,
  isNumericType,
  isSecret,
  isService,
  isStringType,
  listServices,
  PagingOperation,
  PagingProperty,
  PatternData,
  resolveEncodedName,
  serializeValueAsJson,
  Service,
  ServiceDetails,
  VisibilityProvider,
  type BytesKnownEncoding,
  type DateTimeKnownEncoding,
  type DurationKnownEncoding,
  type EncodeData,
  type Example,
  type ExampleOptions,
  type OpExample,
} from "./lib/decorators.js";
export {
  CompileResult,
  createServer,
  TypeSpecLanguageConfiguration,
  type CustomRequestName,
  type InitProjectConfig,
  type InitProjectContext,
  type InitProjectTemplate,
  type InitProjectTemplateEmitterTemplate,
  type InitProjectTemplateLibrarySpec,
  type SemanticToken,
  type SemanticTokenKind,
  type Server,
  type ServerCustomCapacities,
  type ServerHost,
  type ServerInitializeResult,
  type ServerLog,
  type ServerLogLevel,
  type ServerSourceFile,
  type ServerWorkspaceFolder,
} from "./server/index.js";
export type { PackageJson } from "./types/package-json.js";

import { $decorators as intrinsicDecorators } from "./lib/intrinsic/tsp-index.js";
import { $decorators as stdDecorators } from "./lib/tsp-index.js";
/** @internal for Typespec compiler */
export const $decorators = {
  TypeSpec: {
    ...stdDecorators.TypeSpec,
  },
  "TypeSpec.Prototypes": {
    ...intrinsicDecorators["TypeSpec.Prototypes"],
  },
};
