export { resolveCompilerOptions, ResolveCompilerOptionsOptions } from "./config/index.js";
export {
  Checker,
  createChecker,
  CreateTypeProps,
  filterModelProperties,
  finishTypeForProgram,
  getEffectiveModelType,
  getOverriddenProperty,
  TypeSpecCompletionItem,
  walkPropertiesInherited,
} from "./core/checker.js";
export {
  getPropertyType,
  isIntrinsicType,
  isTypeSpecValueTypeOf,
  typespecTypeToJson,
  validateDecoratorNotOnType,
  validateDecoratorParamCount,
  validateDecoratorTarget,
  validateDecoratorUniqueOnNode,
  type DecoratorDefinition,
  type DecoratorParamDefinition,
  type DecoratorValidator,
  type InferredTypeSpecValue,
  type TypeKind,
  type TypeSpecValue,
} from "./core/decorator-utils.js";
export {
  getDeprecationDetails,
  isDeprecated,
  markDeprecated,
  type DeprecationDetails,
} from "./core/deprecation.js";
export {
  assertType,
  compilerAssert,
  createDiagnosticCollector,
  defineCodeFix,
  formatDiagnostic,
  getSourceLocation,
  ignoreDiagnostics,
  logDiagnostics,
  logVerboseTestOutput,
  reportDeprecated,
  type DiagnosticCollector,
  type DiagnosticHandler,
  type SourceLocationOptions,
  type WriteLine,
} from "./core/diagnostics.js";
export { emitFile, type EmitFileOptions, type NewLine } from "./core/emitter-utils.js";
export { checkFormatTypeSpec, formatTypeSpec } from "./core/formatter.js";
export {
  DiscriminatedUnion,
  DiscriminatedUnionLegacy,
  explainStringTemplateNotSerializable,
  printIdentifier as formatIdentifier,
  getDiscriminatedUnion,
  getDiscriminatedUnionFromInheritance,
  getEntityName,
  getLocationContext,
  getNamespaceFullName,
  getTypeName,
  interpolatePath,
  isStdNamespace,
  listOperationsIn,
  printIdentifier,
  resolveUsages,
  TypeNameOptions,
  UsageFlags,
  type ListOperationOptions,
  type OperationContainer,
  type TrackableType,
  type UsageTracker,
} from "./core/helpers/index.js";
export {
  getDiscriminatedTypes,
  getDiscriminator,
  getDocData,
  getMaxItems,
  getMaxItemsAsNumeric,
  getMaxLength,
  getMaxLengthAsNumeric,
  getMaxValue,
  getMaxValueAsNumeric,
  getMaxValueExclusive,
  getMaxValueExclusiveAsNumeric,
  getMinItems,
  getMinItemsAsNumeric,
  getMinLength,
  getMinLengthAsNumeric,
  getMinValue,
  getMinValueAsNumeric,
  getMinValueExclusive,
  getMinValueExclusiveAsNumeric,
  type Discriminator,
} from "./core/intrinsic-type-state.js";
export {
  createLinterRule as createRule,
  createTypeSpecLibrary,
  defineLinter,
  definePackageFlags,
  paramMessage,
  setTypeSpecNamespace,
} from "./core/library.js";
export { resolveLinterDefinition } from "./core/linter.js";
export { NodeHost } from "./core/node-host.js";
export { isNumeric, Numeric } from "./core/numeric.js";
export type { CompilerOptions } from "./core/options.js";
export { getPositionBeforeTrivia } from "./core/parser-utils.js";
export * as TypeSpecPrettierPlugin from "./formatter/index.js";
export {
  $defaultVisibility,
  $discriminator,
  $doc,
  $encode,
  $encodedName,
  $error,
  $errorsDoc,
  $example,
  $format,
  $friendlyName,
  $inspectType,
  $inspectTypeName,
  $invisible,
  $key,
  $maxItems,
  $maxLength,
  $maxValue,
  $maxValueExclusive,
  $minItems,
  $minLength,
  $minValue,
  $minValueExclusive,
  $opExample,
  $overload,
  $parameterVisibility,
  $pattern,
  $removeVisibility,
  $returnsDoc,
  $returnTypeVisibility,
  $secret,
  $service,
  $summary,
  $tag,
  $visibility,
  $withDefaultKeyVisibility,
  $withLifecycleUpdate,
  $withOptionalProperties,
  $withoutDefaultValues,
  $withoutOmittedProperties,
  $withPickedProperties,
  $withUpdateableProperties,
  $withVisibility,
  $withVisibilityFilter,
  addService,
  discriminatedDecorator,
  EmptyVisibilityProvider,
  getAllTags,
  getDeprecated,
  getDoc,
  getEncode,
  getErrorsDoc,
  getErrorsDocData,
  getExamples,
  getFormat,
  getFriendlyName,
  getKeyName,
  getOpExamples,
  getOverloadedOperation,
  getOverloads,
  getPagingOperation,
  getParameterVisibilityFilter,
  getPattern,
  getPatternData,
  getReturnsDoc,
  getReturnsDocData,
  getReturnTypeVisibilityFilter,
  getService,
  getSummary,
  getTags,
  isErrorModel,
  isKey,
  isList,
  isNumericType,
  isSecret,
  isService,
  isStringType,
  listServices,
  PagingOperation,
  PagingProperty,
  PatternData,
  resolveEncodedName,
  serializeValueAsJson,
  Service,
  ServiceDetails,
  VisibilityProvider,
  type BytesKnownEncoding,
  type DateTimeKnownEncoding,
  type DurationKnownEncoding,
  type EncodeData,
  type Example,
  type ExampleOptions,
  type OpExample,
} from "./lib/decorators.js";
export { MANIFEST, typespecVersion, type TypeSpecManifest } from "./manifest.js";
export {
  resolveModule,
  type ModuleResolutionResult,
  type ResolveModuleHost,
  type ResolveModuleOptions,
} from "./module-resolver/module-resolver.js";
export {
  CompileResult,
  createServer,
  TypeSpecLanguageConfiguration,
  type CustomRequestName,
  type InitProjectConfig,
  type InitProjectContext,
  type InitProjectTemplate,
  type InitProjectTemplateEmitterTemplate,
  type InitProjectTemplateLibrarySpec,
  type SemanticToken,
  type SemanticTokenKind,
  type Server,
  type ServerCustomCapacities,
  type ServerHost,
  type ServerInitializeResult,
  type ServerLog,
  type ServerLogLevel,
  type ServerSourceFile,
  type ServerWorkspaceFolder,
} from "./server/index.js";
export type { PackageJson } from "./types/package-json.js";

import { $decorators as intrinsicDecorators } from "./lib/intrinsic/tsp-index.js";
import { $decorators as stdDecorators } from "./lib/tsp-index.js";
/** @internal for Typespec compiler */
export const $decorators = {
  TypeSpec: {
    ...stdDecorators.TypeSpec,
  },
  "TypeSpec.Prototypes": {
    ...intrinsicDecorators["TypeSpec.Prototypes"],
  },
};

export {
  exprIsBareIdentifier,
  getFirstAncestor,
  getIdentifierContext,
  getNodeAtPosition,
  getNodeAtPositionDetail,
  hasParseError,
  isImportStatement,
  parse,
  parseStandaloneTypeReference,
  positionInRange,
  visitChildren,
  type NodeCallback,
} from "./core/parser.js";

export {
  altDirectorySeparator,
  directorySeparator,
  ensureTrailingDirectorySeparator,
  getAnyExtensionFromPath,
  getBaseFileName,
  getDirectoryPath,
  getNormalizedAbsolutePath,
  getNormalizedAbsolutePathWithoutRoot,
  getNormalizedPathComponents,
  getPathComponents,
  getPathFromPathComponents,
  getRelativePathFromDirectory,
  getRootLength,
  hasTrailingDirectorySeparator,
  isAnyDirectorySeparator,
  isPathAbsolute,
  isUrl,
  joinPaths,
  normalizePath,
  normalizeSlashes,
  reducePathComponents,
  removeTrailingDirectorySeparator,
  resolvePath,
} from "./core/path-utils.js";
export { compile, type Program } from "./core/program.js";
export {
  createScanner,
  isComment,
  isKeyword,
  isModifier,
  isPunctuation,
  isStatementKeyword,
  isTrivia,
  skipContinuousIdentifier,
  skipTrivia,
  skipTriviaBackward,
  skipWhiteSpace,
  Token,
  TokenFlags,
  type DocToken,
  type Scanner,
  type StringTemplateToken,
} from "./core/scanner.js";
export {
  getProperty,
  mapEventEmitterToNodeListener,
  navigateProgram,
  navigateType,
  navigateTypesInNamespace,
  scopeNavigationToNamespace,
  type EventEmitter,
  type NamespaceNavigationOptions,
  type NavigationOptions,
} from "./core/semantic-walker.js";
export { createSourceFile, getSourceFileKindFromExt } from "./core/source-file.js";
export {
  getFullyQualifiedSymbolName,
  getParentTemplateNode,
  isArrayModelType,
  isDeclaredInNamespace,
  isDeclaredType,
  isErrorType,
  isGlobalNamespace,
  isNeverType,
  isNullType,
  isRecordModelType,
  isTemplateDeclaration,
  isTemplateDeclarationOrInstance,
  isTemplateInstance,
  isType,
  isUnknownType,
  isValue,
  isVoidType,
} from "./core/type-utils.js";
export {
  ListenerFlow,
  NodeFlags,
  NoTarget,
  ResolutionResultFlags,
  SymbolFlags,
  SyntaxKind,
} from "./core/types.js";
export type {
  AliasStatementNode,
  AnyKeywordNode,
  ArrayExpressionNode,
  ArrayLiteralNode,
  ArrayModelType,
  ArrayValue,
  AugmentDecoratorStatementNode,
  BaseNode,
  BaseType,
  BlockComment,
  BooleanLiteral,
  BooleanLiteralNode,
  BooleanValue,
  CallableMessage,
  CallExpressionNode,
  CodeFix,
  CodeFixContext,
  CodeFixEdit,
  Comment,
  CompilerHost,
  CompilerLocationContext,
  ConstStatementNode,
  Declaration,
  DeclarationNode,
  DecoratedType,
  Decorator,
  DecoratorApplication,
  DecoratorArgument,
  DecoratorArgumentValue,
  DecoratorContext,
  DecoratorDeclarationStatementNode,
  DecoratorExpressionNode,
  DecoratorFunction,
  DecoratorImplementations,
  DeprecatedDirective,
  Diagnostic,
  DiagnosticCreator,
  DiagnosticDefinition,
  DiagnosticFormat,
  DiagnosticMap,
  DiagnosticMessages,
  DiagnosticReport,
  DiagnosticReportWithoutTarget,
  DiagnosticResult,
  DiagnosticSeverity,
  DiagnosticTarget,
  Directive,
  DirectiveArgument,
  DirectiveBase,
  DirectiveExpressionNode,
  Dirent,
  DocContent,
  DocErrorsTagNode,
  DocNode,
  DocParamTagNode,
  DocPropTagNode,
  DocReturnsTagNode,
  DocTag,
  DocTagBaseNode,
  DocTemplateTagNode,
  DocTextNode,
  DocUnknownTagNode,
  EmitContext,
  EmitOptionsFor,
  EmitterFunc,
  EmptyStatementNode,
  Entity,
  Enum,
  EnumMember,
  EnumMemberNode,
  EnumSpreadMemberNode,
  EnumStatementNode,
  EnumValue,
  ErrorType,
  Expression,
  ExternKeywordNode,
  FileLibraryMetadata,
  FilePos,
  FunctionDeclarationStatementNode,
  FunctionParameter,
  FunctionParameterBase,
  FunctionParameterNode,
  IdentifierContext,
  IdentifierKind,
  IdentifierNode,
  ImportStatementNode,
  IndeterminateEntity,
  InsertTextCodeFixEdit,
  Interface,
  InterfaceStatementNode,
  IntersectionExpressionNode,
  IntrinsicScalarName,
  IntrinsicType,
  InvalidStatementNode,
  JsNamespaceDeclarationNode,
  JSONSchemaType,
  JsSourceFileNode,
  LibraryInstance,
  LibraryLocationContext,
  LibraryMetadata,
  LineAndCharacter,
  LineComment,
  LinterDefinition,
  LinterResolvedDefinition,
  LinterRule,
  LinterRuleContext,
  LinterRuleDefinition,
  LinterRuleDiagnosticFormat,
  LinterRuleDiagnosticReport,
  LinterRuleDiagnosticReportWithoutTarget,
  LinterRuleSet,
  LiteralNode,
  LiteralType,
  LocationContext,
  Logger,
  LogInfo,
  LogLevel,
  LogSink,
  MarshalledValue,
  MemberContainerNode,
  MemberContainerType,
  MemberExpressionNode,
  MemberNode,
  MemberType,
  MetaMemberKey,
  MetaMembersTable,
  MixedFunctionParameter,
  MixedParameterConstraint,
  Model,
  ModelExpressionNode,
  ModelIndexer,
  ModelProperty,
  ModelPropertyNode,
  ModelSpreadPropertyNode,
  ModelStatementNode,
  Modifier,
  ModifierFlags,
  ModuleLibraryMetadata,
  MutableSymbolTable,
  Namespace,
  NamespaceStatementNode,
  NeverIndexer,
  NeverKeywordNode,
  NeverType,
  Node,
  NodeLinks,
  NullType,
  NullValue,
  NumericLiteral,
  NumericLiteralNode,
  NumericValue,
  ObjectLiteralNode,
  ObjectLiteralPropertyNode,
  ObjectLiteralSpreadPropertyNode,
  ObjectValue,
  ObjectValuePropertyDescriptor,
  Operation,
  OperationSignature,
  OperationSignatureDeclarationNode,
  OperationSignatureReferenceNode,
  OperationStatementNode,
  PackageFlags,
  ParseOptions,
  PositionDetail,
  ProcessedLog,
  ProjectLocationContext,
  RecordModelType,
  ReferenceExpression,
  RekeyableMap,
  ReplaceTextCodeFixEdit,
  ResolutionResult,
  RmOptions,
  RuleRef,
  Scalar,
  ScalarConstructor,
  ScalarConstructorNode,
  ScalarStatementNode,
  ScalarValue,
  ScopeNode,
  SemanticNodeListener,
  SignatureFunctionParameter,
  SourceFile,
  SourceFileKind,
  SourceLocation,
  SourceModel,
  StateDef,
  Statement,
  StdTypeName,
  StdTypes,
  StringLiteral,
  StringLiteralNode,
  StringTemplate,
  StringTemplateExpressionNode,
  StringTemplateHeadNode,
  StringTemplateLiteralLikeNode,
  StringTemplateMiddleNode,
  StringTemplateSpan,
  StringTemplateSpanLiteral,
  StringTemplateSpanNode,
  StringTemplateSpanValue,
  StringTemplateTailNode,
  StringValue,
  SuppressDirective,
  Sym,
  SymbolLinks,
  SymbolTable,
  SyntheticLocationContext,
  TemplateableNode,
  TemplateArgumentNode,
  TemplateDeclarationNode,
  TemplatedType,
  TemplatedTypeBase,
  TemplateInstanceTarget,
  TemplateParameter,
  TemplateParameterDeclarationNode,
  TextRange,
  Tracer,
  TracerOptions,
  Tuple,
  TupleExpressionNode,
  Type,
  TypeInstantiationMap,
  TypeListeners,
  TypeMapper,
  TypeOfDiagnostics,
  TypeOfExpressionNode,
  TypeReferenceNode,
  TypeSpecDiagnosticTarget,
  TypeSpecLibrary,
  TypeSpecLibraryDef,
  TypeSpecScriptNode,
  Union,
  UnionExpressionNode,
  UnionStatementNode,
  UnionVariant,
  UnionVariantNode,
  UnknownType,
  UsingStatementNode,
  Value,
  ValueOfExpressionNode,
  VoidKeywordNode,
  VoidType,
} from "./core/types.js";
export {
  addVisibilityModifiers,
  clearVisibilityModifiersForClass,
  getLifecycleVisibilityEnum,
  getVisibilityForClass,
  hasVisibility,
  isSealed,
  isVisible,
  removeVisibilityModifiers,
  resetVisibilityModifiersForClass,
  sealVisibilityModifiers,
  sealVisibilityModifiersForProgram,
  VisibilityFilter,
} from "./core/visibility/index.js";
