options:
  "@typespec/http-client-csharp":
    deserialize-null-collection-as-null-value: true
    head-as-boolean: true
    generate-test-project: true
    examples-directory: "{project-root}/examples"
