<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/azure/test.proto

namespace Com\Azure\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.azure.test.Input</code>
 */
class Input extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string testInputField = 1;</code>
     */
    private $testInputField;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $testInputField
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Com\Azure\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string testInputField = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTestInputField()
    {
        return $this->testInputField;
    }

    /**
     * Generated from protobuf field <code>repeated string testInputField = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTestInputField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->testInputField = $arr;

        return $this;
    }

}

