# Continuous Integration

trigger:
  - main
  # For patch releases
  - release/*

pr: none

variables:
  - template: templates/variables/globals.yml

jobs:
  - job: npm_stable
    displayName: Npm publish
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: ./templates/install.yml
      - template: ./templates/build.yml

      - script: pnpm run test-official
        displayName: Test

      - template: ./templates/upload-coverage.yml

      - script: |
          pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          pnpm -r publish --access public --no-git-checks
        displayName: Publish packages

      - script: pnpm run pack:all
        displayName: Pack packages

      - publish: $(Build.SourcesDirectory)/temp/artifacts
        artifact: packages
        displayName: Publish packages(.tgz) as pipeline artifacts

      - publish: $(Build.SourcesDirectory)/packages/typespec-vscode/*.visx
        artifact: vscode-extension
        displayName: Publish VSCode extension(.visx) as pipeline artifacts

      - task: AzureCLI@1
        displayName: "Publish bundled packages to package storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: node ./eng/scripts/upload-bundler-packages.js

      - task: AzureCLI@1
        displayName: "Publish playground"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch ^
              --destination $web ^
              --account-name "cadlplayground" ^
              --destination-path / ^
              --source "./packages/playground-website/dist/" ^
              --overwrite

  - job: publish_vscode
    displayName: Publish VSCode extension
    dependsOn: npm_stable
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    steps:
      - download: current
        artifact: vscode-extension
        displayName: Download VSCode extension(.visx) from pipeline artifacts

      - script: |
          vsix="$(find $(Pipeline.Workspace)/vscode-extension -type f -iname "typespec-vscode-*.vsix" )"

          [ -z "$vsix" ] && echo "Error: Couldn't find vsix" && exit 1

          echo "Found core package $vsix"
          echo "Found modelerfour package $modelerfourPkg"
        displayName: Find packages path

      - template: ./templates/install.yml

      - script: npm run deploy -- --skip-duplicate --packagePath $(Pipeline.Workspace)/vscode-extension/typespec-vscode-*.vsix
        displayName: Publish
        workingDirectory: packages/typespec-vscode
        env:
          VSCE_PAT: $(azuresdk-devdiv-openapi-extension-marketplace-devops-pat)

  - job: npm_dev
    dependsOn: npm_stable
    displayName: Npm publish dev version
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: ./templates/install.yml
      - template: ./templates/build.yml

      - script: node ./packages/internal-build-utils/cmd/cli.js bump-version-preview .
        displayName: Bump version to prerelease targets

      - script: npm run gen-manifest
        displayName: Regen manifest for compiler
        workingDirectory: ./packages/compiler

      - script: |
          pnpm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
          pnpm -r publish --access public --no-git-checks --tag next
        displayName: Publish packages

  - job: docker
    displayName: Docker build and publish
    variables:
      imageName: "azsdkengsys.azurecr.io/typespec"
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04
    steps:
      - task: Docker@1
        displayName: login
        inputs:
          azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
          azureContainerRegistry: azsdkengsys.azurecr.io
          command: login

      - script: |
          docker build -f ./docker/Dockerfile \
            -t $(imageName):latest \
            -t $(imageName):alpine \
            .
        displayName: "Build"

      - script: docker push $(imageName) --all-tags
        displayName: "Push"
