# Continuous Integration

trigger:
  - main
  # For patch releases
  - release/*

pr: none

jobs:
  - job: npm_stable
    displayName: Npm publish
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: Install Node.js

      - task: UseDotNet@2
        inputs:
          version: 6.0.x

      - script: |
          echo ##vso[task.setvariable variable=TYPESPEC_VS_CI_BUILD;]true
        displayName: Enable official Visual Studio extension build

      - script: node common/scripts/install-run-rush.js install
        displayName: Install JavaScript Dependencies

      - script: dotnet restore
        displayName: Restore .NET Dependencies
        workingDirectory: packages/typespec-vs

      - script: node common/scripts/install-run-rush.js rebuild --parallelism max --verbose
        displayName: Build

      - script: node common/scripts/install-run-rush.js test-official --parallelism max --verbose
        displayName: Test

      - template: ./upload-coverage.yml

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public
        displayName: Release

      - task: AzureCLI@1
        displayName: "Publish playground"
        inputs:
          azureSubscription: "Azure SDK Playground"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch ^
              --destination $web ^
              --account-name "cadlplayground" ^
              --destination-path / ^
              --source "./packages/playground/dist/" ^
              --overwrite

  - job: npm_dev
    dependsOn: npm_stable
    displayName: Npm publish dev version
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: Install Node.js

      - script: echo '##vso[task.setvariable variable=TYPESPEC_VS_CI_BUILD;]true'
        displayName: Enable official Visual Studio extension build

      - script: node common/scripts/install-run-rush.js install
        displayName: Install JavaScript Dependencies

      - script: dotnet restore
        displayName: Restore .NET Dependencies
        workingDirectory: packages/typespec-vs

      - script: node common/scripts/install-run-rush.js rebuild --parallelism max --verbose
        displayName: Build

      - script: node ./packages/internal-build-utils/cmd/cli.js bump-version-preview .
        displayName: Bump version to prerelease targets

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public --tag next
        displayName: Release

  - job: docker
    displayName: Docker build and publish
    variables:
      imageName: "azsdkengsys.azurecr.io/typespec"
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04
    steps:
      - task: Docker@1
        displayName: login
        inputs:
          azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
          azureContainerRegistry: azsdkengsys.azurecr.io
          command: login

      - script: |
          docker build -f ./docker/Dockerfile \
            -t $(imageName):latest \
            -t $(imageName):alpine \
            .
        displayName: "Build"

      - script: docker push $(imageName) --all-tags
        displayName: "Push"
