# Continuous Integration

trigger:
  - main
  # For patch releases
  - release/*

pr: none

jobs:
  - job: npm_stable
    displayName: Npm publish
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: ./templates/install.yml
        parameters:
          nodeVersion: "20.x"
      - template: ./templates/build.yml

      - script: node common/scripts/install-run-rush.js test-official --parallelism max --verbose
        displayName: Test

      - template: ./templates/upload-coverage.yml

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public
        displayName: Release

      - task: AzureCLI@1
        displayName: "Publish bundled packages to package storage"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: node ./eng/scripts/upload-bundler-packages.js

      - task: AzureCLI@1
        displayName: "Publish playground"
        inputs:
          azureSubscription: "Azure SDK Engineering System"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch ^
              --destination $web ^
              --account-name "cadlplayground" ^
              --destination-path / ^
              --source "./packages/playground-website/dist/" ^
              --overwrite

  - job: npm_dev
    dependsOn: npm_stable
    displayName: Npm publish dev version
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022

    variables:
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    steps:
      - template: ./templates/install.yml
        parameters:
          nodeVersion: "20.x"
      - template: ./templates/build.yml

      - script: node ./packages/internal-build-utils/cmd/cli.js bump-version-preview .
        displayName: Bump version to prerelease targets

      - script: npm run gen-manifest
        displayName: Regen manifest for compiler
        workingDirectory: ./packages/compiler

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public --tag next
        displayName: Release

  - job: docker
    displayName: Docker build and publish
    variables:
      imageName: "azsdkengsys.azurecr.io/typespec"
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04
    steps:
      - task: Docker@1
        displayName: login
        inputs:
          azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
          azureContainerRegistry: azsdkengsys.azurecr.io
          command: login

      - script: |
          docker build -f ./docker/Dockerfile \
            -t $(imageName):latest \
            -t $(imageName):alpine \
            .
        displayName: "Build"

      - script: docker push $(imageName) --all-tags
        displayName: "Push"
