trigger: none
pr:
  - main
  - release/*

jobs:
  - job: publish_playground
    displayName: Publish playground
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04
    variables:
      TYPESPEC_WEBSITE_BASE_PATH: "prs/$(System.PullRequest.PullRequestNumber)/"
    steps:
      - checkout: self
        persistCredentials: true

      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: Install Node.js

      # purge before install to ensure a clean state between retries
      - script: node common/scripts/install-run-rush.js install --purge
        displayName: Install JavaScript Dependencies
        retryCountOnTaskFailure: 3

      - template: ./templates/build.yml

      - task: AzureCLI@1
        displayName: "Publish playground to PR endpoint"
        inputs:
          azureSubscription: "Azure SDK Playground"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch \
              --destination \$web \
              --account-name "cadlplayground" \
              --destination-path $(TYPESPEC_WEBSITE_BASE_PATH) \
              --source "./packages/playground-website/dist/" \
              --overwrite

      - task: AzureCLI@1
        displayName: "Publish website to PR endpoint"
        inputs:
          azureSubscription: "Azure SDK Playground"
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch \
              --destination \$web \
              --account-name "tspwebsitepr" \
              --destination-path $(TYPESPEC_WEBSITE_BASE_PATH) \
              --source "./packages/website/build/" \
              --overwrite
