trigger:
  - main
pr:
  - main
  - release/*
  - feature/website-design

jobs:
  - job: Build_And_Test
    displayName: Build And Test

    variables:
      TYPESPEC_VS_CI_BUILD: true # Enable official Visual Studio extension build
      TYPESPEC_SKIP_DOCUSAURUS_BUILD: true # Disable docusaurus build

    strategy:
      matrix:
        # Node 16
        "Linux - Node 16.x":
          pool: azsdk-pool-mms-ubuntu-2004-general
          imageName: ubuntu-20.04
          nodeVersion: "16.x"

        "Windows - Node 16.x":
          pool: azsdk-pool-mms-win-2022-general
          imageName: windows-2022
          nodeVersion: "16.x"

        # Node 18
        "Linux - Node 18.x":
          pool: azsdk-pool-mms-ubuntu-2004-general
          imageName: ubuntu-20.04
          nodeVersion: "18.x"

        "Windows - Node 18.x":
          pool: azsdk-pool-mms-win-2022-general
          imageName: windows-2022
          nodeVersion: "18.x"

        # Node 20
        "Linux - Node 20.x":
          pool: azsdk-pool-mms-ubuntu-2004-general
          imageName: ubuntu-20.04
          nodeVersion: "20.5"

        "Windows - Node 20.x":
          pool: azsdk-pool-mms-win-2022-general
          imageName: windows-2022
          nodeVersion: "20.5"

    pool:
      name: $(pool)
      vmImage: $(imageName)

    steps:
      - template: ./jobs/build-and-test.yml
        parameters:
          nodeVersion: $(nodeVersion)
          poolName: $(pool)

  - template: ./jobs/publish-artifacts.yml

  - job: docker_build
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04
    steps:
      - script: docker build -f ./docker/Dockerfile .
        displayName: Docker build

  - job: Consistency_Check
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    steps:
      - template: ./jobs/pull-request-consistency.yml
