// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.clientgenerator.core.methodoverride;

import azure.clientgenerator.core.methodoverride.implementation.GroupParametersImpl;
import azure.clientgenerator.core.methodoverride.models.GroupParametersOptions;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;

/**
 * Initializes a new instance of the synchronous OverrideClient type.
 */
@ServiceClient(builder = OverrideClientBuilder.class)
public final class GroupParametersClient {
    @Generated
    private final GroupParametersImpl serviceClient;

    /**
     * Initializes an instance of GroupParametersClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    GroupParametersClient(GroupParametersImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The group operation.
     * 
     * @param param1 The param1 parameter.
     * @param param2 The param2 parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> groupWithResponse(String param1, String param2, RequestOptions requestOptions) {
        return this.serviceClient.groupWithResponse(param1, param2, requestOptions);
    }

    /**
     * The group operation.
     * 
     * @param options The options parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void group(GroupParametersOptions options) {
        // Generated convenience method for groupWithResponse
        RequestOptions requestOptions = new RequestOptions();
        String param1 = options.getParam1();
        String param2 = options.getParam2();
        groupWithResponse(param1, param2, requestOptions).getValue();
    }
}
