trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packages/http-client-python/

pr: none

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml

  parameters:
    stages:
      - template: /eng/emitters/pipelines/templates/stages/emitter-stages.yml
        parameters:
          BuildPrereleaseVersion: true
          UseTypeSpecNext: false
          Publish: "public"
          PublishDependsOnTest: true
          PackagePath: /packages/http-client-python
          EmitterPackageJsonPath: packages/http-client-python/package.json
          Packages:
            - name: typespec-http-client-python
              file: typespec-http-client-python-*.tgz
              type: npm
          UnitTestArgs: -UnitTests
          StagePrefix: "Python"
          LanguageShortName: "python"
          CadlRanchName: "@typespec/http-client-python"
          EnableCadlRanchReport: false
      - script:
          pnpm chronus version --prerelease --only @typespec/http-client-python
          git add $(Build.SourcesDirectory)/packages/http-client-python
          git checkout -- $(Build.SourcesDirectory)
        displayName: Bump version for dev release of Python client
