# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("main.proto", :syntax => :proto3) do
    add_message "Input" do
      map :testInputField, :sfixed32, :string, 1
    end
  end
end

Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Input").msgclass
