// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.clientgenerator.core.clientlocation.subclient.implementation;

import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;

/**
 * Initializes a new instance of the MoveToExistingSubClient type.
 */
public final class MoveToExistingSubClientImpl {
    /**
     * Service host.
     */
    private final String endpoint;

    /**
     * Gets Service host.
     * 
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * The HTTP pipeline to send requests through.
     */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /**
     * The serializer to serialize an object into a string.
     */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     * 
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /**
     * The AdminOperationsImpl object to access its operations.
     */
    private final AdminOperationsImpl adminOperations;

    /**
     * Gets the AdminOperationsImpl object to access its operations.
     * 
     * @return the AdminOperationsImpl object.
     */
    public AdminOperationsImpl getAdminOperations() {
        return this.adminOperations;
    }

    /**
     * The UserOperationsImpl object to access its operations.
     */
    private final UserOperationsImpl userOperations;

    /**
     * Gets the UserOperationsImpl object to access its operations.
     * 
     * @return the UserOperationsImpl object.
     */
    public UserOperationsImpl getUserOperations() {
        return this.userOperations;
    }

    /**
     * Initializes an instance of MoveToExistingSubClient client.
     * 
     * @param endpoint Service host.
     */
    public MoveToExistingSubClientImpl(String endpoint) {
        this(new HttpPipelineBuilder().policies(new UserAgentPolicy(), new RetryPolicy()).build(),
            JacksonAdapter.createDefaultSerializerAdapter(), endpoint);
    }

    /**
     * Initializes an instance of MoveToExistingSubClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param endpoint Service host.
     */
    public MoveToExistingSubClientImpl(HttpPipeline httpPipeline, String endpoint) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), endpoint);
    }

    /**
     * Initializes an instance of MoveToExistingSubClient client.
     * 
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param endpoint Service host.
     */
    public MoveToExistingSubClientImpl(HttpPipeline httpPipeline, SerializerAdapter serializerAdapter,
        String endpoint) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.endpoint = endpoint;
        this.adminOperations = new AdminOperationsImpl(this);
        this.userOperations = new UserOperationsImpl(this);
    }
}
