// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package payload.multipart;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.azure.core.util.FluxUtil;
import java.util.stream.Collectors;
import payload.multipart.formdata.file.models.UploadFileArrayRequest;
import payload.multipart.formdata.file.models.UploadFileRequiredFilenameRequest;
import payload.multipart.formdata.file.models.UploadFileSpecificContentTypeRequest;
import payload.multipart.implementation.FormDataFilesImpl;
import payload.multipart.implementation.MultipartFormDataHelper;
import payload.multipart.models.FilesFileDetails;
import reactor.core.publisher.Mono;

/**
 * Initializes a new instance of the asynchronous MultiPartClient type.
 */
@ServiceClient(builder = MultiPartClientBuilder.class, isAsync = true)
public final class FormDataFileAsyncClient {
    @Generated
    private final FormDataFilesImpl serviceClient;

    /**
     * Initializes an instance of FormDataFileAsyncClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    FormDataFileAsyncClient(FormDataFilesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The uploadFileSpecificContentType operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Mono<Response<Void>> uploadFileSpecificContentTypeWithResponseInternal(BinaryData body,
        RequestOptions requestOptions) {
        // Operation 'uploadFileSpecificContentType' is of content-type 'multipart/form-data'. Protocol API is not
        // usable and hence not generated.
        return this.serviceClient.uploadFileSpecificContentTypeWithResponseInternalAsync(body, requestOptions);
    }

    /**
     * The uploadFileRequiredFilename operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Mono<Response<Void>> uploadFileRequiredFilenameWithResponseInternal(BinaryData body,
        RequestOptions requestOptions) {
        // Operation 'uploadFileRequiredFilename' is of content-type 'multipart/form-data'. Protocol API is not usable
        // and hence not generated.
        return this.serviceClient.uploadFileRequiredFilenameWithResponseInternalAsync(body, requestOptions);
    }

    /**
     * The uploadFileArray operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Mono<Response<Void>> uploadFileArrayWithResponseInternal(BinaryData body, RequestOptions requestOptions) {
        // Operation 'uploadFileArray' is of content-type 'multipart/form-data'. Protocol API is not usable and hence
        // not generated.
        return this.serviceClient.uploadFileArrayWithResponseInternalAsync(body, requestOptions);
    }

    /**
     * The uploadFileSpecificContentType operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> uploadFileSpecificContentTypeWithResponse(UploadFileSpecificContentTypeRequest body,
        RequestOptions requestOptions) {
        // Generated convenience method for uploadFileSpecificContentTypeWithResponseInternal
        requestOptions = requestOptions == null ? new RequestOptions() : requestOptions;
        return uploadFileSpecificContentTypeWithResponseInternal(
            new MultipartFormDataHelper(requestOptions).serializeFileField("file", body.getFile().getContent(),
                body.getFile().getContentType(), body.getFile().getFilename()).end().getRequestBody(),
            requestOptions);
    }

    /**
     * The uploadFileSpecificContentType operation.
     * 
     * @param body The body parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return A {@link Mono} that completes when a successful response is received.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Void> uploadFileSpecificContentType(UploadFileSpecificContentTypeRequest body) {
        // Generated convenience method for uploadFileSpecificContentTypeWithResponseInternal
        RequestOptions requestOptions = new RequestOptions();
        return uploadFileSpecificContentTypeWithResponseInternal(
            new MultipartFormDataHelper(requestOptions).serializeFileField("file", body.getFile().getContent(),
                body.getFile().getContentType(), body.getFile().getFilename()).end().getRequestBody(),
            requestOptions).flatMap(FluxUtil::toMono);
    }

    /**
     * The uploadFileRequiredFilename operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> uploadFileRequiredFilenameWithResponse(UploadFileRequiredFilenameRequest body,
        RequestOptions requestOptions) {
        // Generated convenience method for uploadFileRequiredFilenameWithResponseInternal
        requestOptions = requestOptions == null ? new RequestOptions() : requestOptions;
        return uploadFileRequiredFilenameWithResponseInternal(
            new MultipartFormDataHelper(requestOptions).serializeFileField("file", body.getFile().getContent(),
                body.getFile().getContentType(), body.getFile().getFilename()).end().getRequestBody(),
            requestOptions);
    }

    /**
     * The uploadFileRequiredFilename operation.
     * 
     * @param body The body parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return A {@link Mono} that completes when a successful response is received.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Void> uploadFileRequiredFilename(UploadFileRequiredFilenameRequest body) {
        // Generated convenience method for uploadFileRequiredFilenameWithResponseInternal
        RequestOptions requestOptions = new RequestOptions();
        return uploadFileRequiredFilenameWithResponseInternal(
            new MultipartFormDataHelper(requestOptions).serializeFileField("file", body.getFile().getContent(),
                body.getFile().getContentType(), body.getFile().getFilename()).end().getRequestBody(),
            requestOptions).flatMap(FluxUtil::toMono);
    }

    /**
     * The uploadFileArray operation.
     * 
     * @param body The body parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> uploadFileArrayWithResponse(UploadFileArrayRequest body,
        RequestOptions requestOptions) {
        // Generated convenience method for uploadFileArrayWithResponseInternal
        requestOptions = requestOptions == null ? new RequestOptions() : requestOptions;
        return uploadFileArrayWithResponseInternal(new MultipartFormDataHelper(requestOptions)
            .serializeFileFields("files",
                body.getFiles().stream().map(FilesFileDetails::getContent).collect(Collectors.toList()),
                body.getFiles().stream().map(FilesFileDetails::getContentType).collect(Collectors.toList()),
                body.getFiles().stream().map(FilesFileDetails::getFilename).collect(Collectors.toList()))
            .end()
            .getRequestBody(), requestOptions);
    }

    /**
     * The uploadFileArray operation.
     * 
     * @param body The body parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return A {@link Mono} that completes when a successful response is received.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Void> uploadFileArray(UploadFileArrayRequest body) {
        // Generated convenience method for uploadFileArrayWithResponseInternal
        RequestOptions requestOptions = new RequestOptions();
        return uploadFileArrayWithResponseInternal(new MultipartFormDataHelper(requestOptions)
            .serializeFileFields("files",
                body.getFiles().stream().map(FilesFileDetails::getContent).collect(Collectors.toList()),
                body.getFiles().stream().map(FilesFileDetails::getContentType).collect(Collectors.toList()),
                body.getFiles().stream().map(FilesFileDetails::getFilename).collect(Collectors.toList()))
            .end()
            .getRequestBody(), requestOptions).flatMap(FluxUtil::toMono);
    }
}
