timeout: 5000
require: source-map-support/register
spec: "dist-dev/test/**/*.test.js"
ignore: "dist-dev/test/manual/**/*.js"

# Config for https://www.npmjs.com/package/mocha-multi-reporters
reporterOptions: "configFile=mocha.reporter.config.json"
