// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package payload.xml;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ServiceClientBuilder;
import com.azure.core.client.traits.ConfigurationTrait;
import com.azure.core.client.traits.EndpointTrait;
import com.azure.core.client.traits.HttpTrait;
import com.azure.core.http.HttpClient;
import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.HttpPipelinePosition;
import com.azure.core.http.policy.AddDatePolicy;
import com.azure.core.http.policy.AddHeadersFromContextPolicy;
import com.azure.core.http.policy.AddHeadersPolicy;
import com.azure.core.http.policy.HttpLogOptions;
import com.azure.core.http.policy.HttpLoggingPolicy;
import com.azure.core.http.policy.HttpPipelinePolicy;
import com.azure.core.http.policy.HttpPolicyProviders;
import com.azure.core.http.policy.RequestIdPolicy;
import com.azure.core.http.policy.RetryOptions;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.ClientOptions;
import com.azure.core.util.Configuration;
import com.azure.core.util.CoreUtils;
import com.azure.core.util.builder.ClientBuilderUtil;
import com.azure.core.util.logging.ClientLogger;
import com.azure.core.util.serializer.JacksonAdapter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import payload.xml.implementation.XmlClientImpl;

/**
 * A builder for creating a new instance of the XmlClient type.
 */
@ServiceClientBuilder(
    serviceClients = {
        SimpleModelValueClient.class,
        ModelWithRenamedPropertyValueClient.class,
        ModelWithRenamedFieldsValueClient.class,
        ModelWithNestedModelValueClient.class,
        ModelWithRenamedNestedModelValueClient.class,
        ModelWithSimpleArraysValueClient.class,
        ModelWithUnwrappedArrayValueClient.class,
        ModelWithRenamedArraysValueClient.class,
        ModelWithWrappedPrimitiveCustomItemNamesValueClient.class,
        ModelWithArrayOfModelValueClient.class,
        ModelWithUnwrappedModelArrayValueClient.class,
        ModelWithRenamedWrappedModelArrayValueClient.class,
        ModelWithRenamedUnwrappedModelArrayValueClient.class,
        ModelWithRenamedWrappedAndItemModelArrayValueClient.class,
        ModelWithAttributesValueClient.class,
        ModelWithRenamedAttributeValueClient.class,
        ModelWithNamespaceValueClient.class,
        ModelWithNamespaceOnPropertiesValueClient.class,
        ModelWithTextValueClient.class,
        ModelWithOptionalFieldValueClient.class,
        ModelWithEmptyArrayValueClient.class,
        ModelWithDictionaryValueClient.class,
        ModelWithEncodedNamesValueClient.class,
        ModelWithEnumValueClient.class,
        ModelWithDatetimeValueClient.class,
        XmlErrorValueClient.class,
        SimpleModelValueAsyncClient.class,
        ModelWithRenamedPropertyValueAsyncClient.class,
        ModelWithRenamedFieldsValueAsyncClient.class,
        ModelWithNestedModelValueAsyncClient.class,
        ModelWithRenamedNestedModelValueAsyncClient.class,
        ModelWithSimpleArraysValueAsyncClient.class,
        ModelWithUnwrappedArrayValueAsyncClient.class,
        ModelWithRenamedArraysValueAsyncClient.class,
        ModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient.class,
        ModelWithArrayOfModelValueAsyncClient.class,
        ModelWithUnwrappedModelArrayValueAsyncClient.class,
        ModelWithRenamedWrappedModelArrayValueAsyncClient.class,
        ModelWithRenamedUnwrappedModelArrayValueAsyncClient.class,
        ModelWithRenamedWrappedAndItemModelArrayValueAsyncClient.class,
        ModelWithAttributesValueAsyncClient.class,
        ModelWithRenamedAttributeValueAsyncClient.class,
        ModelWithNamespaceValueAsyncClient.class,
        ModelWithNamespaceOnPropertiesValueAsyncClient.class,
        ModelWithTextValueAsyncClient.class,
        ModelWithOptionalFieldValueAsyncClient.class,
        ModelWithEmptyArrayValueAsyncClient.class,
        ModelWithDictionaryValueAsyncClient.class,
        ModelWithEncodedNamesValueAsyncClient.class,
        ModelWithEnumValueAsyncClient.class,
        ModelWithDatetimeValueAsyncClient.class,
        XmlErrorValueAsyncClient.class })
public final class XmlClientBuilder
    implements HttpTrait<XmlClientBuilder>, ConfigurationTrait<XmlClientBuilder>, EndpointTrait<XmlClientBuilder> {
    @Generated
    private static final String SDK_NAME = "name";

    @Generated
    private static final String SDK_VERSION = "version";

    @Generated
    private static final Map<String, String> PROPERTIES = CoreUtils.getProperties("payload-xml.properties");

    @Generated
    private final List<HttpPipelinePolicy> pipelinePolicies;

    /**
     * Create an instance of the XmlClientBuilder.
     */
    @Generated
    public XmlClientBuilder() {
        this.pipelinePolicies = new ArrayList<>();
    }

    /*
     * The HTTP client used to send the request.
     */
    @Generated
    private HttpClient httpClient;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder httpClient(HttpClient httpClient) {
        this.httpClient = httpClient;
        return this;
    }

    /*
     * The HTTP pipeline to send requests through.
     */
    @Generated
    private HttpPipeline pipeline;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder pipeline(HttpPipeline pipeline) {
        if (this.pipeline != null && pipeline == null) {
            LOGGER.atInfo().log("HttpPipeline is being set to 'null' when it was previously configured.");
        }
        this.pipeline = pipeline;
        return this;
    }

    /*
     * The logging configuration for HTTP requests and responses.
     */
    @Generated
    private HttpLogOptions httpLogOptions;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder httpLogOptions(HttpLogOptions httpLogOptions) {
        this.httpLogOptions = httpLogOptions;
        return this;
    }

    /*
     * The client options such as application ID and custom headers to set on a request.
     */
    @Generated
    private ClientOptions clientOptions;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder clientOptions(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        return this;
    }

    /*
     * The retry options to configure retry policy for failed requests.
     */
    @Generated
    private RetryOptions retryOptions;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder retryOptions(RetryOptions retryOptions) {
        this.retryOptions = retryOptions;
        return this;
    }

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder addPolicy(HttpPipelinePolicy customPolicy) {
        Objects.requireNonNull(customPolicy, "'customPolicy' cannot be null.");
        pipelinePolicies.add(customPolicy);
        return this;
    }

    /*
     * The configuration store that is used during construction of the service client.
     */
    @Generated
    private Configuration configuration;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder configuration(Configuration configuration) {
        this.configuration = configuration;
        return this;
    }

    /*
     * The service endpoint
     */
    @Generated
    private String endpoint;

    /**
     * {@inheritDoc}.
     */
    @Generated
    @Override
    public XmlClientBuilder endpoint(String endpoint) {
        this.endpoint = endpoint;
        return this;
    }

    /*
     * The retry policy that will attempt to retry failed requests, if applicable.
     */
    @Generated
    private RetryPolicy retryPolicy;

    /**
     * Sets The retry policy that will attempt to retry failed requests, if applicable.
     * 
     * @param retryPolicy the retryPolicy value.
     * @return the XmlClientBuilder.
     */
    @Generated
    public XmlClientBuilder retryPolicy(RetryPolicy retryPolicy) {
        this.retryPolicy = retryPolicy;
        return this;
    }

    /**
     * Builds an instance of XmlClientImpl with the provided parameters.
     * 
     * @return an instance of XmlClientImpl.
     */
    @Generated
    private XmlClientImpl buildInnerClient() {
        this.validateClient();
        HttpPipeline localPipeline = (pipeline != null) ? pipeline : createHttpPipeline();
        String localEndpoint = (endpoint != null) ? endpoint : "http://localhost:3000";
        XmlClientImpl client
            = new XmlClientImpl(localPipeline, JacksonAdapter.createDefaultSerializerAdapter(), localEndpoint);
        return client;
    }

    @Generated
    private void validateClient() {
        // This method is invoked from 'buildInnerClient'/'buildClient' method.
        // Developer can customize this method, to validate that the necessary conditions are met for the new client.
    }

    @Generated
    private HttpPipeline createHttpPipeline() {
        Configuration buildConfiguration
            = (configuration == null) ? Configuration.getGlobalConfiguration() : configuration;
        HttpLogOptions localHttpLogOptions = this.httpLogOptions == null ? new HttpLogOptions() : this.httpLogOptions;
        ClientOptions localClientOptions = this.clientOptions == null ? new ClientOptions() : this.clientOptions;
        List<HttpPipelinePolicy> policies = new ArrayList<>();
        String clientName = PROPERTIES.getOrDefault(SDK_NAME, "UnknownName");
        String clientVersion = PROPERTIES.getOrDefault(SDK_VERSION, "UnknownVersion");
        String applicationId = CoreUtils.getApplicationId(localClientOptions, localHttpLogOptions);
        policies.add(new UserAgentPolicy(applicationId, clientName, clientVersion, buildConfiguration));
        policies.add(new RequestIdPolicy());
        policies.add(new AddHeadersFromContextPolicy());
        HttpHeaders headers = CoreUtils.createHttpHeadersFromClientOptions(localClientOptions);
        if (headers != null) {
            policies.add(new AddHeadersPolicy(headers));
        }
        this.pipelinePolicies.stream()
            .filter(p -> p.getPipelinePosition() == HttpPipelinePosition.PER_CALL)
            .forEach(p -> policies.add(p));
        HttpPolicyProviders.addBeforeRetryPolicies(policies);
        policies.add(ClientBuilderUtil.validateAndGetRetryPolicy(retryPolicy, retryOptions, new RetryPolicy()));
        policies.add(new AddDatePolicy());
        this.pipelinePolicies.stream()
            .filter(p -> p.getPipelinePosition() == HttpPipelinePosition.PER_RETRY)
            .forEach(p -> policies.add(p));
        HttpPolicyProviders.addAfterRetryPolicies(policies);
        policies.add(new HttpLoggingPolicy(localHttpLogOptions));
        HttpPipeline httpPipeline = new HttpPipelineBuilder().policies(policies.toArray(new HttpPipelinePolicy[0]))
            .httpClient(httpClient)
            .clientOptions(localClientOptions)
            .build();
        return httpPipeline;
    }

    /**
     * Builds an instance of SimpleModelValueAsyncClient class.
     * 
     * @return an instance of SimpleModelValueAsyncClient.
     */
    @Generated
    public SimpleModelValueAsyncClient buildSimpleModelValueAsyncClient() {
        return new SimpleModelValueAsyncClient(buildInnerClient().getSimpleModelValues());
    }

    /**
     * Builds an instance of ModelWithRenamedPropertyValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedPropertyValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedPropertyValueAsyncClient buildModelWithRenamedPropertyValueAsyncClient() {
        return new ModelWithRenamedPropertyValueAsyncClient(buildInnerClient().getModelWithRenamedPropertyValues());
    }

    /**
     * Builds an instance of ModelWithRenamedFieldsValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedFieldsValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedFieldsValueAsyncClient buildModelWithRenamedFieldsValueAsyncClient() {
        return new ModelWithRenamedFieldsValueAsyncClient(buildInnerClient().getModelWithRenamedFieldsValues());
    }

    /**
     * Builds an instance of ModelWithNestedModelValueAsyncClient class.
     * 
     * @return an instance of ModelWithNestedModelValueAsyncClient.
     */
    @Generated
    public ModelWithNestedModelValueAsyncClient buildModelWithNestedModelValueAsyncClient() {
        return new ModelWithNestedModelValueAsyncClient(buildInnerClient().getModelWithNestedModelValues());
    }

    /**
     * Builds an instance of ModelWithRenamedNestedModelValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedNestedModelValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedNestedModelValueAsyncClient buildModelWithRenamedNestedModelValueAsyncClient() {
        return new ModelWithRenamedNestedModelValueAsyncClient(
            buildInnerClient().getModelWithRenamedNestedModelValues());
    }

    /**
     * Builds an instance of ModelWithSimpleArraysValueAsyncClient class.
     * 
     * @return an instance of ModelWithSimpleArraysValueAsyncClient.
     */
    @Generated
    public ModelWithSimpleArraysValueAsyncClient buildModelWithSimpleArraysValueAsyncClient() {
        return new ModelWithSimpleArraysValueAsyncClient(buildInnerClient().getModelWithSimpleArraysValues());
    }

    /**
     * Builds an instance of ModelWithUnwrappedArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithUnwrappedArrayValueAsyncClient.
     */
    @Generated
    public ModelWithUnwrappedArrayValueAsyncClient buildModelWithUnwrappedArrayValueAsyncClient() {
        return new ModelWithUnwrappedArrayValueAsyncClient(buildInnerClient().getModelWithUnwrappedArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedArraysValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedArraysValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedArraysValueAsyncClient buildModelWithRenamedArraysValueAsyncClient() {
        return new ModelWithRenamedArraysValueAsyncClient(buildInnerClient().getModelWithRenamedArraysValues());
    }

    /**
     * Builds an instance of ModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient class.
     * 
     * @return an instance of ModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient.
     */
    @Generated
    public ModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient
        buildModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient() {
        return new ModelWithWrappedPrimitiveCustomItemNamesValueAsyncClient(
            buildInnerClient().getModelWithWrappedPrimitiveCustomItemNamesValues());
    }

    /**
     * Builds an instance of ModelWithArrayOfModelValueAsyncClient class.
     * 
     * @return an instance of ModelWithArrayOfModelValueAsyncClient.
     */
    @Generated
    public ModelWithArrayOfModelValueAsyncClient buildModelWithArrayOfModelValueAsyncClient() {
        return new ModelWithArrayOfModelValueAsyncClient(buildInnerClient().getModelWithArrayOfModelValues());
    }

    /**
     * Builds an instance of ModelWithUnwrappedModelArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithUnwrappedModelArrayValueAsyncClient.
     */
    @Generated
    public ModelWithUnwrappedModelArrayValueAsyncClient buildModelWithUnwrappedModelArrayValueAsyncClient() {
        return new ModelWithUnwrappedModelArrayValueAsyncClient(
            buildInnerClient().getModelWithUnwrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedWrappedModelArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedWrappedModelArrayValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedWrappedModelArrayValueAsyncClient buildModelWithRenamedWrappedModelArrayValueAsyncClient() {
        return new ModelWithRenamedWrappedModelArrayValueAsyncClient(
            buildInnerClient().getModelWithRenamedWrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedUnwrappedModelArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedUnwrappedModelArrayValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedUnwrappedModelArrayValueAsyncClient
        buildModelWithRenamedUnwrappedModelArrayValueAsyncClient() {
        return new ModelWithRenamedUnwrappedModelArrayValueAsyncClient(
            buildInnerClient().getModelWithRenamedUnwrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedWrappedAndItemModelArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedWrappedAndItemModelArrayValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedWrappedAndItemModelArrayValueAsyncClient
        buildModelWithRenamedWrappedAndItemModelArrayValueAsyncClient() {
        return new ModelWithRenamedWrappedAndItemModelArrayValueAsyncClient(
            buildInnerClient().getModelWithRenamedWrappedAndItemModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithAttributesValueAsyncClient class.
     * 
     * @return an instance of ModelWithAttributesValueAsyncClient.
     */
    @Generated
    public ModelWithAttributesValueAsyncClient buildModelWithAttributesValueAsyncClient() {
        return new ModelWithAttributesValueAsyncClient(buildInnerClient().getModelWithAttributesValues());
    }

    /**
     * Builds an instance of ModelWithRenamedAttributeValueAsyncClient class.
     * 
     * @return an instance of ModelWithRenamedAttributeValueAsyncClient.
     */
    @Generated
    public ModelWithRenamedAttributeValueAsyncClient buildModelWithRenamedAttributeValueAsyncClient() {
        return new ModelWithRenamedAttributeValueAsyncClient(buildInnerClient().getModelWithRenamedAttributeValues());
    }

    /**
     * Builds an instance of ModelWithNamespaceValueAsyncClient class.
     * 
     * @return an instance of ModelWithNamespaceValueAsyncClient.
     */
    @Generated
    public ModelWithNamespaceValueAsyncClient buildModelWithNamespaceValueAsyncClient() {
        return new ModelWithNamespaceValueAsyncClient(buildInnerClient().getModelWithNamespaceValues());
    }

    /**
     * Builds an instance of ModelWithNamespaceOnPropertiesValueAsyncClient class.
     * 
     * @return an instance of ModelWithNamespaceOnPropertiesValueAsyncClient.
     */
    @Generated
    public ModelWithNamespaceOnPropertiesValueAsyncClient buildModelWithNamespaceOnPropertiesValueAsyncClient() {
        return new ModelWithNamespaceOnPropertiesValueAsyncClient(
            buildInnerClient().getModelWithNamespaceOnPropertiesValues());
    }

    /**
     * Builds an instance of ModelWithTextValueAsyncClient class.
     * 
     * @return an instance of ModelWithTextValueAsyncClient.
     */
    @Generated
    public ModelWithTextValueAsyncClient buildModelWithTextValueAsyncClient() {
        return new ModelWithTextValueAsyncClient(buildInnerClient().getModelWithTextValues());
    }

    /**
     * Builds an instance of ModelWithOptionalFieldValueAsyncClient class.
     * 
     * @return an instance of ModelWithOptionalFieldValueAsyncClient.
     */
    @Generated
    public ModelWithOptionalFieldValueAsyncClient buildModelWithOptionalFieldValueAsyncClient() {
        return new ModelWithOptionalFieldValueAsyncClient(buildInnerClient().getModelWithOptionalFieldValues());
    }

    /**
     * Builds an instance of ModelWithEmptyArrayValueAsyncClient class.
     * 
     * @return an instance of ModelWithEmptyArrayValueAsyncClient.
     */
    @Generated
    public ModelWithEmptyArrayValueAsyncClient buildModelWithEmptyArrayValueAsyncClient() {
        return new ModelWithEmptyArrayValueAsyncClient(buildInnerClient().getModelWithEmptyArrayValues());
    }

    /**
     * Builds an instance of ModelWithDictionaryValueAsyncClient class.
     * 
     * @return an instance of ModelWithDictionaryValueAsyncClient.
     */
    @Generated
    public ModelWithDictionaryValueAsyncClient buildModelWithDictionaryValueAsyncClient() {
        return new ModelWithDictionaryValueAsyncClient(buildInnerClient().getModelWithDictionaryValues());
    }

    /**
     * Builds an instance of ModelWithEncodedNamesValueAsyncClient class.
     * 
     * @return an instance of ModelWithEncodedNamesValueAsyncClient.
     */
    @Generated
    public ModelWithEncodedNamesValueAsyncClient buildModelWithEncodedNamesValueAsyncClient() {
        return new ModelWithEncodedNamesValueAsyncClient(buildInnerClient().getModelWithEncodedNamesValues());
    }

    /**
     * Builds an instance of ModelWithEnumValueAsyncClient class.
     * 
     * @return an instance of ModelWithEnumValueAsyncClient.
     */
    @Generated
    public ModelWithEnumValueAsyncClient buildModelWithEnumValueAsyncClient() {
        return new ModelWithEnumValueAsyncClient(buildInnerClient().getModelWithEnumValues());
    }

    /**
     * Builds an instance of ModelWithDatetimeValueAsyncClient class.
     * 
     * @return an instance of ModelWithDatetimeValueAsyncClient.
     */
    @Generated
    public ModelWithDatetimeValueAsyncClient buildModelWithDatetimeValueAsyncClient() {
        return new ModelWithDatetimeValueAsyncClient(buildInnerClient().getModelWithDatetimeValues());
    }

    /**
     * Builds an instance of XmlErrorValueAsyncClient class.
     * 
     * @return an instance of XmlErrorValueAsyncClient.
     */
    @Generated
    public XmlErrorValueAsyncClient buildXmlErrorValueAsyncClient() {
        return new XmlErrorValueAsyncClient(buildInnerClient().getXmlErrorValues());
    }

    /**
     * Builds an instance of SimpleModelValueClient class.
     * 
     * @return an instance of SimpleModelValueClient.
     */
    @Generated
    public SimpleModelValueClient buildSimpleModelValueClient() {
        return new SimpleModelValueClient(buildInnerClient().getSimpleModelValues());
    }

    /**
     * Builds an instance of ModelWithRenamedPropertyValueClient class.
     * 
     * @return an instance of ModelWithRenamedPropertyValueClient.
     */
    @Generated
    public ModelWithRenamedPropertyValueClient buildModelWithRenamedPropertyValueClient() {
        return new ModelWithRenamedPropertyValueClient(buildInnerClient().getModelWithRenamedPropertyValues());
    }

    /**
     * Builds an instance of ModelWithRenamedFieldsValueClient class.
     * 
     * @return an instance of ModelWithRenamedFieldsValueClient.
     */
    @Generated
    public ModelWithRenamedFieldsValueClient buildModelWithRenamedFieldsValueClient() {
        return new ModelWithRenamedFieldsValueClient(buildInnerClient().getModelWithRenamedFieldsValues());
    }

    /**
     * Builds an instance of ModelWithNestedModelValueClient class.
     * 
     * @return an instance of ModelWithNestedModelValueClient.
     */
    @Generated
    public ModelWithNestedModelValueClient buildModelWithNestedModelValueClient() {
        return new ModelWithNestedModelValueClient(buildInnerClient().getModelWithNestedModelValues());
    }

    /**
     * Builds an instance of ModelWithRenamedNestedModelValueClient class.
     * 
     * @return an instance of ModelWithRenamedNestedModelValueClient.
     */
    @Generated
    public ModelWithRenamedNestedModelValueClient buildModelWithRenamedNestedModelValueClient() {
        return new ModelWithRenamedNestedModelValueClient(buildInnerClient().getModelWithRenamedNestedModelValues());
    }

    /**
     * Builds an instance of ModelWithSimpleArraysValueClient class.
     * 
     * @return an instance of ModelWithSimpleArraysValueClient.
     */
    @Generated
    public ModelWithSimpleArraysValueClient buildModelWithSimpleArraysValueClient() {
        return new ModelWithSimpleArraysValueClient(buildInnerClient().getModelWithSimpleArraysValues());
    }

    /**
     * Builds an instance of ModelWithUnwrappedArrayValueClient class.
     * 
     * @return an instance of ModelWithUnwrappedArrayValueClient.
     */
    @Generated
    public ModelWithUnwrappedArrayValueClient buildModelWithUnwrappedArrayValueClient() {
        return new ModelWithUnwrappedArrayValueClient(buildInnerClient().getModelWithUnwrappedArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedArraysValueClient class.
     * 
     * @return an instance of ModelWithRenamedArraysValueClient.
     */
    @Generated
    public ModelWithRenamedArraysValueClient buildModelWithRenamedArraysValueClient() {
        return new ModelWithRenamedArraysValueClient(buildInnerClient().getModelWithRenamedArraysValues());
    }

    /**
     * Builds an instance of ModelWithWrappedPrimitiveCustomItemNamesValueClient class.
     * 
     * @return an instance of ModelWithWrappedPrimitiveCustomItemNamesValueClient.
     */
    @Generated
    public ModelWithWrappedPrimitiveCustomItemNamesValueClient
        buildModelWithWrappedPrimitiveCustomItemNamesValueClient() {
        return new ModelWithWrappedPrimitiveCustomItemNamesValueClient(
            buildInnerClient().getModelWithWrappedPrimitiveCustomItemNamesValues());
    }

    /**
     * Builds an instance of ModelWithArrayOfModelValueClient class.
     * 
     * @return an instance of ModelWithArrayOfModelValueClient.
     */
    @Generated
    public ModelWithArrayOfModelValueClient buildModelWithArrayOfModelValueClient() {
        return new ModelWithArrayOfModelValueClient(buildInnerClient().getModelWithArrayOfModelValues());
    }

    /**
     * Builds an instance of ModelWithUnwrappedModelArrayValueClient class.
     * 
     * @return an instance of ModelWithUnwrappedModelArrayValueClient.
     */
    @Generated
    public ModelWithUnwrappedModelArrayValueClient buildModelWithUnwrappedModelArrayValueClient() {
        return new ModelWithUnwrappedModelArrayValueClient(buildInnerClient().getModelWithUnwrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedWrappedModelArrayValueClient class.
     * 
     * @return an instance of ModelWithRenamedWrappedModelArrayValueClient.
     */
    @Generated
    public ModelWithRenamedWrappedModelArrayValueClient buildModelWithRenamedWrappedModelArrayValueClient() {
        return new ModelWithRenamedWrappedModelArrayValueClient(
            buildInnerClient().getModelWithRenamedWrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedUnwrappedModelArrayValueClient class.
     * 
     * @return an instance of ModelWithRenamedUnwrappedModelArrayValueClient.
     */
    @Generated
    public ModelWithRenamedUnwrappedModelArrayValueClient buildModelWithRenamedUnwrappedModelArrayValueClient() {
        return new ModelWithRenamedUnwrappedModelArrayValueClient(
            buildInnerClient().getModelWithRenamedUnwrappedModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithRenamedWrappedAndItemModelArrayValueClient class.
     * 
     * @return an instance of ModelWithRenamedWrappedAndItemModelArrayValueClient.
     */
    @Generated
    public ModelWithRenamedWrappedAndItemModelArrayValueClient
        buildModelWithRenamedWrappedAndItemModelArrayValueClient() {
        return new ModelWithRenamedWrappedAndItemModelArrayValueClient(
            buildInnerClient().getModelWithRenamedWrappedAndItemModelArrayValues());
    }

    /**
     * Builds an instance of ModelWithAttributesValueClient class.
     * 
     * @return an instance of ModelWithAttributesValueClient.
     */
    @Generated
    public ModelWithAttributesValueClient buildModelWithAttributesValueClient() {
        return new ModelWithAttributesValueClient(buildInnerClient().getModelWithAttributesValues());
    }

    /**
     * Builds an instance of ModelWithRenamedAttributeValueClient class.
     * 
     * @return an instance of ModelWithRenamedAttributeValueClient.
     */
    @Generated
    public ModelWithRenamedAttributeValueClient buildModelWithRenamedAttributeValueClient() {
        return new ModelWithRenamedAttributeValueClient(buildInnerClient().getModelWithRenamedAttributeValues());
    }

    /**
     * Builds an instance of ModelWithNamespaceValueClient class.
     * 
     * @return an instance of ModelWithNamespaceValueClient.
     */
    @Generated
    public ModelWithNamespaceValueClient buildModelWithNamespaceValueClient() {
        return new ModelWithNamespaceValueClient(buildInnerClient().getModelWithNamespaceValues());
    }

    /**
     * Builds an instance of ModelWithNamespaceOnPropertiesValueClient class.
     * 
     * @return an instance of ModelWithNamespaceOnPropertiesValueClient.
     */
    @Generated
    public ModelWithNamespaceOnPropertiesValueClient buildModelWithNamespaceOnPropertiesValueClient() {
        return new ModelWithNamespaceOnPropertiesValueClient(
            buildInnerClient().getModelWithNamespaceOnPropertiesValues());
    }

    /**
     * Builds an instance of ModelWithTextValueClient class.
     * 
     * @return an instance of ModelWithTextValueClient.
     */
    @Generated
    public ModelWithTextValueClient buildModelWithTextValueClient() {
        return new ModelWithTextValueClient(buildInnerClient().getModelWithTextValues());
    }

    /**
     * Builds an instance of ModelWithOptionalFieldValueClient class.
     * 
     * @return an instance of ModelWithOptionalFieldValueClient.
     */
    @Generated
    public ModelWithOptionalFieldValueClient buildModelWithOptionalFieldValueClient() {
        return new ModelWithOptionalFieldValueClient(buildInnerClient().getModelWithOptionalFieldValues());
    }

    /**
     * Builds an instance of ModelWithEmptyArrayValueClient class.
     * 
     * @return an instance of ModelWithEmptyArrayValueClient.
     */
    @Generated
    public ModelWithEmptyArrayValueClient buildModelWithEmptyArrayValueClient() {
        return new ModelWithEmptyArrayValueClient(buildInnerClient().getModelWithEmptyArrayValues());
    }

    /**
     * Builds an instance of ModelWithDictionaryValueClient class.
     * 
     * @return an instance of ModelWithDictionaryValueClient.
     */
    @Generated
    public ModelWithDictionaryValueClient buildModelWithDictionaryValueClient() {
        return new ModelWithDictionaryValueClient(buildInnerClient().getModelWithDictionaryValues());
    }

    /**
     * Builds an instance of ModelWithEncodedNamesValueClient class.
     * 
     * @return an instance of ModelWithEncodedNamesValueClient.
     */
    @Generated
    public ModelWithEncodedNamesValueClient buildModelWithEncodedNamesValueClient() {
        return new ModelWithEncodedNamesValueClient(buildInnerClient().getModelWithEncodedNamesValues());
    }

    /**
     * Builds an instance of ModelWithEnumValueClient class.
     * 
     * @return an instance of ModelWithEnumValueClient.
     */
    @Generated
    public ModelWithEnumValueClient buildModelWithEnumValueClient() {
        return new ModelWithEnumValueClient(buildInnerClient().getModelWithEnumValues());
    }

    /**
     * Builds an instance of ModelWithDatetimeValueClient class.
     * 
     * @return an instance of ModelWithDatetimeValueClient.
     */
    @Generated
    public ModelWithDatetimeValueClient buildModelWithDatetimeValueClient() {
        return new ModelWithDatetimeValueClient(buildInnerClient().getModelWithDatetimeValues());
    }

    /**
     * Builds an instance of XmlErrorValueClient class.
     * 
     * @return an instance of XmlErrorValueClient.
     */
    @Generated
    public XmlErrorValueClient buildXmlErrorValueClient() {
        return new XmlErrorValueClient(buildInnerClient().getXmlErrorValues());
    }

    private static final ClientLogger LOGGER = new ClientLogger(XmlClientBuilder.class);
}
