// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the implementations for Numeric.
 * Test for encode decorator on integer.
 * <!-- end generated doc -->
 */
package com.encode.numeric.implementation;
