// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * <!-- start generated doc -->
 * Package containing the classes for ClientLocation.
 * Test for &#064;clientLocation decorator - moving operations between clients.
 * <!-- end generated doc -->
 */
package azure.clientgenerator.core.clientlocation;
