// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the service clients for ArmResourceProvider.
 * Arm Resource Provider management API.
 */
package com.cadl.armresourceprovider.fluent;
