jobs:
  - job: sign_vscode
    displayName: Sign
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    steps:
      - checkout: none
      - download: current
        artifact: vscode-extension-unsigned
        displayName: Download VSCode extension(.vsix) from pipeline artifacts

      - template: ../templates/sign-vsix.yml
        parameters:
          path: $(Pipeline.Workspace)/vscode-extension-unsigned
          pattern: "*.vsix"

      - publish: $(Pipeline.Workspace)/vscode-extension-unsigned
        artifact: vscode-extension-signed
        displayName: Publish signed VSCode extension

  - job: publish_vscode
    displayName: Publish
    dependsOn: sign_vscode
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: ubuntu-20.04

    steps:
      - download: current
        artifact: vscode-extension-signed
        displayName: Download VSCode extension(.vsix) from pipeline artifacts

      - template: ../templates/install.yml

      - script: npm run deploy -- --skip-duplicate --packagePath $(Pipeline.Workspace)/vscode-extension/typespec-vscode-*.vsix
        displayName: Publish
        workingDirectory: packages/typespec-vscode
        env:
          VSCE_PAT: $(azuresdk-devdiv-openapi-extension-marketplace-devops-pat)
