// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package payload.pageable.serverdrivenpagination.continuationtoken.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The RequestQueryNestedResponseBodyResponseNestedNext model.
 */
@Immutable
public final class RequestQueryNestedResponseBodyResponseNestedNext
    implements JsonSerializable<RequestQueryNestedResponseBodyResponseNestedNext> {
    /*
     * The nextToken property.
     */
    @Generated
    private String nextToken;

    /**
     * Creates an instance of RequestQueryNestedResponseBodyResponseNestedNext class.
     */
    @Generated
    private RequestQueryNestedResponseBodyResponseNestedNext() {
    }

    /**
     * Get the nextToken property: The nextToken property.
     * 
     * @return the nextToken value.
     */
    @Generated
    public String getNextToken() {
        return this.nextToken;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("nextToken", this.nextToken);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RequestQueryNestedResponseBodyResponseNestedNext from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RequestQueryNestedResponseBodyResponseNestedNext if the JsonReader was pointing to an
     * instance of it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RequestQueryNestedResponseBodyResponseNestedNext.
     */
    @Generated
    public static RequestQueryNestedResponseBodyResponseNestedNext fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RequestQueryNestedResponseBodyResponseNestedNext deserializedRequestQueryNestedResponseBodyResponseNestedNext
                = new RequestQueryNestedResponseBodyResponseNestedNext();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("nextToken".equals(fieldName)) {
                    deserializedRequestQueryNestedResponseBodyResponseNestedNext.nextToken = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRequestQueryNestedResponseBodyResponseNestedNext;
        });
    }
}
