parameters:
  "service-dir":
    default: "sdk/signalr"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/signalr.json"
    examples-dir: "{project-root}/examples"
    arm-resource-flattening: true
    emit-lro-options: "all"
  "@azure-tools/typespec-csharp":
    flavor: azure
    package-dir: "Azure.ResourceManager.SignalR"
    clear-output-folder: true
    model-namespace: true
    namespace: "{package-dir}"
    examples-dir: "{project-root}/examples"
    enable-bicep-serialization: true
  "@typespec/http-client-python":
    package-dir: "azure-mgmt-signalr"
    namespace: "azure.mgmt.signalr"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-signalr"
    namespace: "com.azure.resourcemanager.signalr"
    service-name: "SignalR"
    flavor: azure
    resource-collection-associations:
      - resource: SignalRResource
        collection: SignalR
  "@azure-tools/typespec-ts":
    package-dir: "arm-signalr"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-signalr"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/signalr"
    package-dir: "armsignalr"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/{package-dir}"
    fix-const-stuttering: false
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
