// <auto-generated/>

#nullable disable

using System.ClientModel;
using System.ClientModel.Primitives;

#pragma warning disable SCME0004 // Type is for evaluation purposes only and is subject to change or removal in future updates.
namespace Sample.Models
{
    public partial class AllPrimitivesRequest
    {
        internal AllPrimitivesRequest()
        {
        }

        internal global::System.ClientModel.MultiPartFormContent ToMultipartFormContent(global::System.ClientModel.Primitives.ModelReaderWriterOptions options)
        {
            global::System.ClientModel.MultiPartFormContent content = new global::System.ClientModel.MultiPartFormContent();

            content.Add("stringPart", StringPart);
            content.Add("boolPart", BoolPart);
            content.Add("int32Part", Int32Part);
            content.Add("int64Part", Int64Part);
            content.Add("float32Part", Float32Part);
            content.Add("float64Part", Float64Part);
            content.Add("decimalPart", DecimalPart);
            content.Add("sbytePart", SbytePart);
            content.Add("bytePart", BytePart, "text/plain");
            content.Add("binaryDataPart", BinaryDataPart.WithMediaType("text/plain"));

            return content;
        }
    }
}
#pragma warning restore SCME0004 // Type is for evaluation purposes only and is subject to change or removal in future updates.
