// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package azure.resourcemanager.multiservicesharedmodels.combined.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Storage account properties.
 */
@Fluent
public final class StorageAccountProperties implements JsonSerializable<StorageAccountProperties> {
    /*
     * The provisioningState property.
     */
    private ResourceProvisioningState provisioningState;

    /*
     * Shared metadata for the storage account.
     */
    private SharedMetadata metadata;

    /**
     * Creates an instance of StorageAccountProperties class.
     */
    public StorageAccountProperties() {
    }

    /**
     * Get the provisioningState property: The provisioningState property.
     * 
     * @return the provisioningState value.
     */
    public ResourceProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Get the metadata property: Shared metadata for the storage account.
     * 
     * @return the metadata value.
     */
    public SharedMetadata metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata property: Shared metadata for the storage account.
     * 
     * @param metadata the metadata value to set.
     * @return the StorageAccountProperties object itself.
     */
    public StorageAccountProperties withMetadata(SharedMetadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("metadata", this.metadata);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of StorageAccountProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of StorageAccountProperties if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the StorageAccountProperties.
     */
    public static StorageAccountProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            StorageAccountProperties deserializedStorageAccountProperties = new StorageAccountProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("provisioningState".equals(fieldName)) {
                    deserializedStorageAccountProperties.provisioningState
                        = ResourceProvisioningState.fromString(reader.getString());
                } else if ("metadata".equals(fieldName)) {
                    deserializedStorageAccountProperties.metadata = SharedMetadata.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedStorageAccountProperties;
        });
    }
}
