// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package tsptest.armresourceprovider.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.core.management.Resource;
import com.azure.core.management.SystemData;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.Map;
import tsptest.armresourceprovider.models.CustomTemplateResourcePropertiesAnonymousEmptyModel;
import tsptest.armresourceprovider.models.Dog;
import tsptest.armresourceprovider.models.EmptyModel;
import tsptest.armresourceprovider.models.ManagedServiceIdentity;
import tsptest.armresourceprovider.models.PriorityModel;
import tsptest.armresourceprovider.models.ProvisioningState;

/**
 * Concrete tracked resource types can be created by aliasing this type using a specific property type.
 */
@Fluent
public final class CustomTemplateResourceInner extends Resource {
    /*
     * The resource-specific properties for this resource.
     */
    @Generated
    private CustomTemplateResourceProperties innerProperties;

    /*
     * Managed identity.
     */
    @Generated
    private ManagedServiceIdentity identity;

    /*
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    @Generated
    private SystemData systemData;

    /*
     * The type of the resource.
     */
    @Generated
    private String type;

    /*
     * The name of the resource.
     */
    @Generated
    private String name;

    /*
     * Fully qualified resource Id for the resource.
     */
    @Generated
    private String id;

    /**
     * Creates an instance of CustomTemplateResourceInner class.
     */
    @Generated
    public CustomTemplateResourceInner() {
    }

    /**
     * Get the innerProperties property: The resource-specific properties for this resource.
     * 
     * @return the innerProperties value.
     */
    @Generated
    private CustomTemplateResourceProperties innerProperties() {
        return this.innerProperties;
    }

    /**
     * Get the identity property: Managed identity.
     * 
     * @return the identity value.
     */
    @Generated
    public ManagedServiceIdentity identity() {
        return this.identity;
    }

    /**
     * Set the identity property: Managed identity.
     * 
     * @param identity the identity value to set.
     * @return the CustomTemplateResourceInner object itself.
     */
    @Generated
    public CustomTemplateResourceInner withIdentity(ManagedServiceIdentity identity) {
        this.identity = identity;
        return this;
    }

    /**
     * Get the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    @Generated
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Get the type property: The type of the resource.
     * 
     * @return the type value.
     */
    @Generated
    @Override
    public String type() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Generated
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    @Generated
    @Override
    public String id() {
        return this.id;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public CustomTemplateResourceInner withLocation(String location) {
        super.withLocation(location);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public CustomTemplateResourceInner withTags(Map<String, String> tags) {
        super.withTags(tags);
        return this;
    }

    /**
     * Get the provisioningState property: The status of the last operation.
     * 
     * @return the provisioningState value.
     */
    @Generated
    public ProvisioningState provisioningState() {
        return this.innerProperties() == null ? null : this.innerProperties().provisioningState();
    }

    /**
     * Get the dog property: The dog property.
     * 
     * @return the dog value.
     */
    @Generated
    public Dog dog() {
        return this.innerProperties() == null ? null : this.innerProperties().dog();
    }

    /**
     * Set the dog property: The dog property.
     * 
     * @param dog the dog value to set.
     * @return the CustomTemplateResourceInner object itself.
     */
    @Generated
    public CustomTemplateResourceInner withDog(Dog dog) {
        if (this.innerProperties() == null) {
            this.innerProperties = new CustomTemplateResourceProperties();
        }
        this.innerProperties().withDog(dog);
        return this;
    }

    /**
     * Get the namedEmptyModel property: The namedEmptyModel property.
     * 
     * @return the namedEmptyModel value.
     */
    @Generated
    public EmptyModel namedEmptyModel() {
        return this.innerProperties() == null ? null : this.innerProperties().namedEmptyModel();
    }

    /**
     * Set the namedEmptyModel property: The namedEmptyModel property.
     * 
     * @param namedEmptyModel the namedEmptyModel value to set.
     * @return the CustomTemplateResourceInner object itself.
     */
    @Generated
    public CustomTemplateResourceInner withNamedEmptyModel(EmptyModel namedEmptyModel) {
        if (this.innerProperties() == null) {
            this.innerProperties = new CustomTemplateResourceProperties();
        }
        this.innerProperties().withNamedEmptyModel(namedEmptyModel);
        return this;
    }

    /**
     * Get the anonymousEmptyModel property: The anonymousEmptyModel property.
     * 
     * @return the anonymousEmptyModel value.
     */
    @Generated
    public CustomTemplateResourcePropertiesAnonymousEmptyModel anonymousEmptyModel() {
        return this.innerProperties() == null ? null : this.innerProperties().anonymousEmptyModel();
    }

    /**
     * Set the anonymousEmptyModel property: The anonymousEmptyModel property.
     * 
     * @param anonymousEmptyModel the anonymousEmptyModel value to set.
     * @return the CustomTemplateResourceInner object itself.
     */
    @Generated
    public CustomTemplateResourceInner
        withAnonymousEmptyModel(CustomTemplateResourcePropertiesAnonymousEmptyModel anonymousEmptyModel) {
        if (this.innerProperties() == null) {
            this.innerProperties = new CustomTemplateResourceProperties();
        }
        this.innerProperties().withAnonymousEmptyModel(anonymousEmptyModel);
        return this;
    }

    /**
     * Get the priority property: The priority property.
     * 
     * @return the priority value.
     */
    @Generated
    public PriorityModel priority() {
        return this.innerProperties() == null ? null : this.innerProperties().priority();
    }

    /**
     * Set the priority property: The priority property.
     * 
     * @param priority the priority value to set.
     * @return the CustomTemplateResourceInner object itself.
     */
    @Generated
    public CustomTemplateResourceInner withPriority(PriorityModel priority) {
        if (this.innerProperties() == null) {
            this.innerProperties = new CustomTemplateResourceProperties();
        }
        this.innerProperties().withPriority(priority);
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (innerProperties() != null) {
            innerProperties().validate();
        }
        if (identity() != null) {
            identity().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("location", location());
        jsonWriter.writeMapField("tags", tags(), (writer, element) -> writer.writeString(element));
        jsonWriter.writeJsonField("properties", this.innerProperties);
        jsonWriter.writeJsonField("identity", this.identity);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CustomTemplateResourceInner from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CustomTemplateResourceInner if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CustomTemplateResourceInner.
     */
    public static CustomTemplateResourceInner fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            CustomTemplateResourceInner deserializedCustomTemplateResourceInner = new CustomTemplateResourceInner();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.type = reader.getString();
                } else if ("location".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.withLocation(reader.getString());
                } else if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedCustomTemplateResourceInner.withTags(tags);
                } else if ("properties".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.innerProperties
                        = CustomTemplateResourceProperties.fromJson(reader);
                } else if ("identity".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.identity = ManagedServiceIdentity.fromJson(reader);
                } else if ("systemData".equals(fieldName)) {
                    deserializedCustomTemplateResourceInner.systemData = SystemData.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedCustomTemplateResourceInner;
        });
    }
}
