trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - packages/http-client-csharp/
      - eng/emitters/
      - eng/common/

extends:
  template: /eng/emitters/pipelines/templates/archetype-emitter.yml
  parameters:
    BuildPrereleaseVersion: true
    UseTypeSpecNext: false
    Publish: "none"
    PackagePath: /packages/http-client-csharp
    EmitterPackageJsonPath: packages/http-client-csharp/package.json
    Packages:
      - name: emitter
        file: typespec-http-client-csharp-*.tgz
        type: npm
    UnitTestArgs: -UnitTests
