trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packages/http-client-csharp/
    exclude:
      - packages/http-client-csharp/eng/

pr: none

parameters:
  - name: CreateAzureSdkForNetPR
    displayName: Create PR for azure-sdk-for-net
    type: boolean
    default: false

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml

  parameters:
    stages:
      - template: /eng/emitters/pipelines/templates/stages/emitter-stages.yml
        parameters:
          BuildPrereleaseVersion: true
          UseTypeSpecNext: false
          Publish: ${{replace(replace('True',eq(variables['Build.SourceBranchName'], 'main'), 'public'),'True','internal')}}
          PublishDependsOnTest: true
          PackagePath: /packages/http-client-csharp
          EmitterPackageJsonPath: packages/http-client-csharp/package.json
          Packages:
            - name: typespec-http-client-csharp
              file: typespec-http-client-csharp-*.tgz
              type: npm
            - name: Microsoft.TypeSpec.Generator
              file: Microsoft.TypeSpec.Generator.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.ClientModel
              file: Microsoft.TypeSpec.Generator.ClientModel.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.Input
              file: Microsoft.TypeSpec.Generator.Input.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.Customization
              file: Microsoft.TypeSpec.Generator.Customization.*.nupkg
              type: nuget
          UnitTestArgs: -UnitTests
          StagePrefix: "CSharp"
          LanguageShortName: "csharp"
          HasNugetPackages: true
          CadlRanchName: "@typespec/http-client-csharp"
          AdditionalInitializeSteps:
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 8"
                performMultiLevelLookup: true
                useGlobalJson: false
                version: 8.x
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 9"
                performMultiLevelLookup: true
                useGlobalJson: false
                version: 9.x
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 10"
                performMultiLevelLookup: true
                useGlobalJson: true
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp

      - stage: CreateAzureSdkForNetPR
        displayName: Create PR for azure-sdk-for-net
        dependsOn:
          - CSharp_Publish
          - CSharp_Build
        condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'main'), and(eq(variables['Build.Reason'], 'Manual'), ${{ parameters.CreateAzureSdkForNetPR }})))
        variables:
          PackageVersion: $[ stageDependencies.CSharp_Build.Build_linux_20.outputs['ci_build.emitterVersion'] ]
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: CreatePR
            steps:
              - checkout: self
              - pwsh: |
                  # Determine the TypeSpec PR URL 
                  $repoUrl = '$(Build.Repository.Uri)'.TrimEnd('/')
                  $commitSha = '$(Build.SourceVersion)'
                  $typeSpecCommitUrl = "$repoUrl/commit/$commitSha"

                  Write-Host "Commit SHA: $commitSha"
                  Write-Host "TypeSpec Commit URL: $typeSpecCommitUrl"
                  Write-Host "##vso[task.setvariable variable=TypeSpecCommitUrl]$typeSpecCommitUrl"
                displayName: Set variables for PR creation

              - task: UseNode@1
                displayName: "Install Node.js"
                inputs:
                  version: "22.x"

              - task: NuGetAuthenticate@1

              - pwsh: |
                  Write-Host "Creating .npmrc file $(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc for registry https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-js-test-autorest/npm/registry/"
                  $parentFolder = Split-Path -Path '$(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc' -Parent
                  
                  if (!(Test-Path $parentFolder)) {
                    Write-Host "Creating folder $parentFolder"
                    New-Item -Path $parentFolder -ItemType Directory | Out-Null
                  }
                  
                  $content = "registry=https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-js-test-autorest/npm/registry/`n`nalways-auth=true"
                  $content | Out-File '$(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc'
                  
                  Write-Host "##[section].npmrc file created successfully. Contents:"
                  Get-Content '$(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc' | ForEach-Object { Write-Host "  $_" }
                displayName: 'Create .npmrc'
                condition: eq('${{replace(replace('True',eq(variables['Build.SourceBranchName'], 'main'), 'public'),'True','internal')}}', 'internal')

              - task: npmAuthenticate@0
                displayName: Authenticate npm for Azure Artifacts
                condition: eq('${{replace(replace('True',eq(variables['Build.SourceBranchName'], 'main'), 'public'),'True','internal')}}', 'internal')
                inputs:
                  workingFile: $(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc

              - download: current
                displayName: Download pipeline artifacts

              - pwsh: |
                  npm install -g @azure-tools/typespec-client-generator-cli@latest
                displayName: Install tsp-client

              - task: PowerShell@2
                displayName: Update package.json with injected dependencies
                inputs:
                  pwsh: true
                  filePath: $(Build.SourcesDirectory)/packages/http-client-csharp/eng/scripts/Update-PackageJson.ps1
                  workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
                  arguments: >
                    -PackageVersion '$(PackageVersion)'
                    -PackageJsonPath '$(Build.SourcesDirectory)/packages/http-client-csharp/package.json'

              - task: UseDotNet@2
                inputs:
                  useGlobalJson: true
                  workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp

              - pwsh: |
                  Write-Host "##[section]Checking npm configuration before PR submission..."
                  Write-Host "Current npm registry:"
                  npm config get registry
                  
                  Write-Host "`nChecking for .npmrc files:"
                  $npmrcPath = "$(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc"
                  if (Test-Path $npmrcPath) {
                    Write-Host "Found .npmrc at: $npmrcPath"
                    Write-Host "Contents (excluding auth tokens):"
                    Get-Content $npmrcPath | Where-Object { $_ -notmatch ':_password|:_authToken' } | ForEach-Object { Write-Host "  $_" }
                  } else {
                    Write-Host ".npmrc file not found - will use default npm registry"
                  }
                  
                  Write-Host "`nNpm config list (user + global):"
                  npm config list
                displayName: 'Log npm configuration'
                condition: eq(${{ parameters.CreateAzureSdkForNetPR }}, true)

              - task: PowerShell@2
                displayName: Generate emitter-package.json files & create PR in azure-sdk-for-net
                inputs:
                  pwsh: true
                  filePath: $(Build.SourcesDirectory)/packages/http-client-csharp/eng/scripts/Submit-AzureSdkForNetPr.ps1
                  arguments: >
                    -PackageVersion '$(PackageVersion)'
                    -TypeSpecCommitUrl '$(TypeSpecCommitUrl)'
                    -AuthToken '$(azuresdk-github-pat)'
                    -TypeSpecSourcePackageJsonPath '$(Build.SourcesDirectory)/packages/http-client-csharp/package.json'

              - pwsh: |
                  $npmrcPath = "$(Build.SourcesDirectory)/packages/http-client-csharp/.npmrc"
                  if (Test-Path $npmrcPath) {
                    Remove-Item $npmrcPath -Force
                    Write-Host "Cleaned up .npmrc file"
                  }
                displayName: Cleanup .npmrc file
                condition: always()

