# Manual trigger for Regen Preview Pipeline
# This pipeline regenerates libraries in azure-sdk-for-net and creates a draft PR with the changes
trigger: none

pr: none

parameters:
  - name: LibraryType
    displayName: Library Type to Regenerate
    type: string
    default: All
    values:
      - All
      - Unbranded
      - Azure
      - Mgmt

extends:
  template: /eng/common/pipelines/templates/1es-redirect.yml

  parameters:
    stages:
      # Build stage - Build the emitter packages
      - template: /eng/emitters/pipelines/templates/stages/emitter-stages.yml
        parameters:
          BuildPrereleaseVersion: true
          UseTypeSpecNext: false
          Publish: "none"
          PackagePath: /packages/http-client-csharp
          EmitterPackageJsonPath: packages/http-client-csharp/package.json
          Packages:
            - name: typespec-http-client-csharp
              file: typespec-http-client-csharp-*.tgz
              type: npm
            - name: Microsoft.TypeSpec.Generator
              file: Microsoft.TypeSpec.Generator.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.ClientModel
              file: Microsoft.TypeSpec.Generator.ClientModel.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.Input
              file: Microsoft.TypeSpec.Generator.Input.*.nupkg
              type: nuget
            - name: Microsoft.TypeSpec.Generator.Customization
              file: Microsoft.TypeSpec.Generator.Customization.*.nupkg
              type: nuget
          UnitTestArgs: -UnitTests
          StagePrefix: "CSharp"
          LanguageShortName: "csharp"
          HasNugetPackages: true
          CadlRanchName: "@typespec/http-client-csharp"
          AdditionalInitializeSteps:
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 8"
                performMultiLevelLookup: true
                useGlobalJson: false
                version: 8.x
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 9"
                performMultiLevelLookup: true
                useGlobalJson: false
                version: 9.x
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
            - task: UseDotNet@2
              inputs:
                displayName: "Install .NET 10"
                performMultiLevelLookup: true
                useGlobalJson: true
                workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp

      # Regen Preview stage - Run RegenPreview.ps1 and create PR
      - stage: RegenPreview
        displayName: Regenerate Libraries and Create PR
        dependsOn:
          - CSharp_Build
        condition: succeeded()
        variables:
          PackageVersion: $[ stageDependencies.CSharp_Build.Build_linux_20.outputs['ci_build.emitterVersion'] ]
        pool:
          name: $(LINUXPOOL)
          image: $(LINUXVMIMAGE)
          os: linux
        jobs:
          - job: RunRegenPreview
            displayName: Run Regeneration Preview
            steps:
              - checkout: self

              - task: UseNode@1
                displayName: "Install Node.js"
                inputs:
                  version: "22.x"

              - task: NuGetAuthenticate@1

              - download: current
                displayName: Download pipeline artifacts

              - pwsh: |
                  npm install -g @azure-tools/typespec-client-generator-cli@latest
                displayName: Install tsp-client

              - task: PowerShell@2
                displayName: Update package.json with injected dependencies
                inputs:
                  pwsh: true
                  filePath: $(Build.SourcesDirectory)/packages/http-client-csharp/eng/scripts/Update-PackageJson.ps1
                  workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
                  arguments: >
                    -PackageVersion '$(PackageVersion)'
                    -PackageJsonPath '$(Build.SourcesDirectory)/packages/http-client-csharp/package.json'

              - task: UseDotNet@2
                inputs:
                  useGlobalJson: true
                  workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp

              # Clone azure-sdk-for-net repository
              - pwsh: |
                  $tempDir = Join-Path ([System.IO.Path]::GetTempPath()) "azure-sdk-for-net-regen-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
                  New-Item -ItemType Directory -Path $tempDir -Force | Out-Null
                  Write-Host "Created temp directory: $tempDir"
                  Write-Host "##vso[task.setvariable variable=AzureSdkRepoPath]$tempDir"

                  # Clone azure-sdk-for-net with sparse checkout
                  Write-Host "Cloning azure-sdk-for-net repository with sparse checkout..."
                  git init $tempDir
                  if ($LASTEXITCODE -ne 0) { throw "Failed to initialize repository" }

                  Push-Location $tempDir
                  try {
                    git remote add origin "https://github.com/Azure/azure-sdk-for-net.git"
                    if ($LASTEXITCODE -ne 0) { throw "Failed to add remote" }

                    git sparse-checkout init --cone
                    if ($LASTEXITCODE -ne 0) { throw "Failed to initialize sparse checkout" }

                    git sparse-checkout set eng/packages/http-client-csharp eng sdk
                    if ($LASTEXITCODE -ne 0) { throw "Failed to set sparse checkout patterns" }

                    git fetch --depth 1 origin main
                    if ($LASTEXITCODE -ne 0) { throw "Failed to fetch from origin" }

                    git checkout main
                    if ($LASTEXITCODE -ne 0) { throw "Failed to checkout main branch" }

                    Write-Host "Successfully cloned azure-sdk-for-net"
                  }
                  finally {
                    Pop-Location
                  }
                displayName: Clone azure-sdk-for-net repository

              # Run RegenPreview.ps1
              - task: PowerShell@2
                displayName: Run RegenPreview.ps1
                continueOnError: true
                inputs:
                  pwsh: true
                  workingDirectory: $(Build.SourcesDirectory)/packages/http-client-csharp
                  targetType: inline
                  script: |
                    $ErrorActionPreference = 'Continue'

                    # Determine script arguments based on LibraryType parameter
                    $scriptArgs = @(
                      '-SdkLibraryRepoPath', '$(AzureSdkRepoPath)'
                    )

                    $libraryType = '${{ parameters.LibraryType }}'
                    if ($libraryType -ne 'All') {
                      $scriptArgs += "-$libraryType"
                    }

                    Write-Host "Running RegenPreview.ps1 with arguments: $($scriptArgs -join ' ')"

                    try {
                      & $(Build.SourcesDirectory)/packages/http-client-csharp/eng/scripts/RegenPreview.ps1 @scriptArgs
                      $exitCode = $LASTEXITCODE
                      Write-Host "RegenPreview.ps1 completed with exit code: $exitCode"
                      Write-Host "##vso[task.setvariable variable=RegenExitCode]$exitCode"

                      if ($exitCode -eq 0) {
                        Write-Host "##vso[task.setvariable variable=RegenSuccess]true"
                      } else {
                        Write-Host "##vso[task.setvariable variable=RegenSuccess]false"
                      }
                    }
                    catch {
                      Write-Host "Error running RegenPreview.ps1: $_"
                      Write-Host "##vso[task.setvariable variable=RegenSuccess]false"
                      Write-Host "##vso[task.setvariable variable=RegenExitCode]1"
                    }

              # Upload regen-report.json as artifact
              - task: PublishPipelineArtifact@1
                displayName: Upload regen-report.json
                condition: always()
                inputs:
                  targetPath: '$(Build.SourcesDirectory)/packages/http-client-csharp/regen-report.json'
                  artifactName: 'regen-report'
                  publishLocation: 'pipeline'

              # Set TypeSpec commit URL variable
              - pwsh: |
                  $repoUrl = '$(Build.Repository.Uri)'.TrimEnd('/')
                  $commitSha = '$(Build.SourceVersion)'
                  $typeSpecCommitUrl = "$repoUrl/commit/$commitSha"
                  Write-Host "##vso[task.setvariable variable=TypeSpecCommitUrl]$typeSpecCommitUrl"
                displayName: Set TypeSpec commit URL

              # Create PR in azure-sdk-for-net
              - task: PowerShell@2
                displayName: Create PR in azure-sdk-for-net
                condition: always()
                inputs:
                  pwsh: true
                  filePath: $(Build.SourcesDirectory)/packages/http-client-csharp/eng/scripts/Submit-RegenPreviewPr.ps1
                  arguments: >
                    -PackageVersion '$(PackageVersion)'
                    -TypeSpecCommitUrl '$(TypeSpecCommitUrl)'
                    -AuthToken '$(azuresdk-github-pat)'
                    -AzureSdkRepoPath '$(AzureSdkRepoPath)'
                    -RegenSuccess $${{ eq(variables['RegenSuccess'], 'true') }}
                    -BranchName 'regen-preview/http-client-csharp-$(PackageVersion)-$(Build.BuildId)'
                    -BuildUri '$(Build.BuildUri)'
