name: Merge release branch back into main

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "release/*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  # Create PR
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate branch name
        id: branchname
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "branchname=backmerge/${REF_NAME}-$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: Create branch
        env:
          BRANCH: ${{ steps.branchname.outputs.branchname }}
        run: |
          git checkout -b "$BRANCH"
          git push --set-upstream origin "$BRANCH"
