name: Python Integration

on:
  workflow_call:
  pull_request:
    branches: ["main"]
    paths:
      - "packages/http-client-python/**"
      - ".github/workflows/ci-python-template.yml"
      - ".github/workflows/python-integration.yml"
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-python-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Regenerate"
    if: |
      !startsWith(github.head_ref, 'dependabot/') &&
      !startsWith(github.head_ref, 'publish/') &&
      !startsWith(github.head_ref, 'backmerge/') &&
      !startsWith(github.head_ref, 'revert-')
    uses: ./.github/workflows/ci-python-template.yml
    with:
      check: build
      use-typespec-azure: true

  test:
    name: "Mock API Tests"
    needs: build
    uses: ./.github/workflows/ci-python-template.yml
    with:
      check: test
      use-typespec-azure: true

  typecheck:
    name: "Type Checking"
    needs: build
    uses: ./.github/workflows/ci-python-template.yml
    with:
      check: typecheck
      use-typespec-azure: true

  lint:
    name: "Lint & Format"
    needs: build
    uses: ./.github/workflows/ci-python-template.yml
    with:
      check: lint
      use-typespec-azure: true

  docs:
    name: "Docs Validation"
    needs: build
    uses: ./.github/workflows/ci-python-template.yml
    with:
      check: docs
      use-typespec-azure: true
