name: Sync labels

on:
  push:
    branches: ["main", "label-sync"]
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: pnpm sync-labels --update-github-labels --dry-run
        name: Sync labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
