name: Sync labels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "label-sync"]
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/setup

      - run: pnpm tsx ./eng/common/scripts/sync-labels.ts --update-github-labels --dry-run
        name: Sync labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
