name: Azure TypeSpec Integration Check

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'packages/http-client-csharp/**'
      - 'packages/http-client-java/**'
      - 'packages/http-client-python/**'
      - 'website/**'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      run:
        description: 'Run this workflow'
        required: false
        default: 'true'

# This check is optional by default
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  azure-integration-check:
    name: Check Azure/typespec-azure compatibility
    runs-on: ubuntu-latest
    # Only run if not from dependabot, publish, backmerge, or revert branches
    if: |
      !startsWith(github.head_ref, 'dependabot/') &&
      !startsWith(github.head_ref, 'publish/') &&
      !startsWith(github.head_ref, 'backmerge/') &&
      !startsWith(github.head_ref, 'revert-')
    
    steps:
      - name: Checkout TypeSpec repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x # Using current LTS
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      
      - name: Checkout Azure/typespec-azure repo
        uses: actions/checkout@v4
        with:
          repository: Azure/typespec-azure
          path: typespec-azure
          submodules: true
      
      - name: Update core submodule to PR changes
        run: |
          cd typespec-azure
          
          # Core submodule is located at ./core
          echo "Updating core submodule to PR changes"
          
          # Point the submodule to our PR changes
          git config -f .gitmodules submodule.core.url "$GITHUB_WORKSPACE"
          
          # Navigate to the core submodule directory
          cd core
          
          # Use the PR changes
          git checkout ${{ github.event.pull_request.head.sha }}
          
          # Go back to the typespec-azure root
          cd $GITHUB_WORKSPACE/typespec-azure
      
      - name: Install dependencies for typespec-azure
        run: |
          echo "::group::Installing dependencies"
          cd typespec-azure
          
          echo "Node.js version:"
          node --version
          
          echo "pnpm version:"
          pnpm --version
          
          echo "Installing dependencies..."
          pnpm install
          
          echo "✅ Dependencies installed"
          echo "::endgroup::"
      
      - name: Build
        run: |
          cd typespec-azure
          pnpm build
      
      - name: Run tests for typespec-azure
        run: |
          echo "::group::Running tests"
          cd typespec-azure
          
          echo "Running tests..."
          pnpm test
          
          echo "✅ Tests passed"
          echo "::endgroup::"