name: Azure TypeSpec Integration Check

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'packages/http-client-csharp/**'
      - 'packages/http-client-java/**'
      - 'packages/http-client-python/**'
      - 'website/**'
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      run:
        description: 'Run this workflow'
        required: false
        default: 'true'

# This check is optional by default
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  azure-integration-check:
    name: Check Azure/typespec-azure compatibility
    runs-on: ubuntu-latest
    # Only run if not from dependabot, publish, backmerge, or revert branches
    if: |
      !startsWith(github.head_ref, 'dependabot/') &&
      !startsWith(github.head_ref, 'publish/') &&
      !startsWith(github.head_ref, 'backmerge/') &&
      !startsWith(github.head_ref, 'revert-')
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x # Using current LTS
      
      - name: Checkout Azure/typespec-azure repo
        uses: actions/checkout@v4
        with:
          repository: Azure/typespec-azure
          submodules: true
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      
      - name: Checkout TypeSpec PR code
        uses: actions/checkout@v4
        with:
          path: typespec-pr
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Replace core submodule with PR code
        run: rm -rf core && cp -r typespec-pr core
      
      - name: Install
        run: pnpm install
      
      - name: Build
        run: pnpm build
      
      - name: Test
        run: pnpm test